import type { TrainingFocus } from './trainingFocus';

/**
 * The training plan generator.
 *
 * ## It is rules, and it is named as rules
 *
 * This is a deterministic function: the same answers produce the same plan,
 * every time, with no model and no network. That is a deliberate choice, not a
 * limitation to apologise for — this project has already shipped a chatbot that
 * invented gyms, coaches and prices that do not exist, and a plan that quietly
 * makes things up in front of a member is worse than one that is predictable.
 *
 * The vocabulary stays honest to match. Nothing in the interface calls this AI.
 *
 * ## Built so a model can be added later without touching this file
 *
 * `buildPlan` returns a **PlanSpec** — structured data, no prose. Turning that
 * into words happens in `planRender.ts`. That seam is the whole point: a hybrid
 * that wants a model to reword the plan conversationally replaces the renderer
 * and leaves the programming logic alone, so the facts stay generated by rules
 * that can be audited and the model only ever changes the phrasing. The stored
 * row keeps the spec, not the prose, so an old plan can be re-rendered by
 * whatever the app uses at the time.
 *
 * ## What it will not do
 *
 * No calorie targets, no macro splits, no weight goals. `trainingFocus.ts`
 * already sets the rule this follows:
 *
 *     These sentences describe the direction of a tape measurement against a
 *     stated intention. They do not say a member is healthy, unhealthy, on
 *     track, or failing, and they never suggest what anyone should eat or weigh.
 *
 * Individual dietary prescription from a lookup table is not something this can
 * do responsibly — it has no idea who is pregnant, diabetic, recovering from an
 * eating disorder, or sixteen. So nutrition here is general practice, the same
 * things a coach would say out loud on the gym floor, and anything individual
 * routes to a human. Nor does it program around injuries: a stated limitation
 * produces a referral to a trainer, never a modified exercise.
 */

export type Experience = 'beginner' | 'intermediate' | 'advanced';
export type Preference = 'gym' | 'classes' | 'both';

export interface PlanInputs {
  experience: Experience;
  focus: TrainingFocus;
  /** Realistic sessions per week. Clamped to 2-6; below 2 is not a programme. */
  daysPerWeek: number;
  /** Minutes per session, as the member actually has, not as they wish. */
  sessionMinutes: 30 | 45 | 60 | 90;
  preference: Preference;
  /** Free text. Its presence changes the plan's advice, never its exercises. */
  limitations: string;
}

export interface PlanExercise {
  name: string;
  sets: number;
  reps: string;
  /** Shown under the exercise. Technique cue or a substitution, never a claim. */
  note?: string;
}

export interface PlanDay {
  label: string;
  focus: string;
  exercises: PlanExercise[];
}

export interface PlanSpec {
  /** Schema version, so a stored plan can be re-rendered years later. */
  version: 1;
  builtAt: string;
  inputs: PlanInputs;
  splitName: string;
  /** Why this split, in the member's terms. */
  rationale: string;
  days: PlanDay[];
  conditioning: string[];
  progression: string[];
  nutrition: string[];
  /** Reasons to talk to an actual coach. Never empty. */
  seeACoach: string[];
}

/* ─────────────────────────────────────────────────────────────────────────────
   Exercise pools.

   Deliberately small and equipment-light: this is one gym in Mamburao, not a
   catalogue. Every movement here needs a barbell, dumbbells, a bench, a bar to
   pull on, or nothing at all. A plan that programmes a hack squat the gym does
   not own is a plan the member cannot follow.
   ───────────────────────────────────────────────────────────────────────────*/

const PUSH = {
  primary: [
    { name: 'Barbell bench press', note: 'Dumbbells are fine if the bench is busy.' },
    { name: 'Overhead press', note: 'Standing or seated — keep the ribs down.' },
  ],
  secondary: [
    { name: 'Incline dumbbell press' },
    { name: 'Dips', note: 'Bench dips if the bars are too much for now.' },
    { name: 'Lateral raise', note: 'Light. This one is not meant to feel heavy.' },
    { name: 'Triceps pushdown or overhead extension' },
  ],
};

const PULL = {
  primary: [
    { name: 'Barbell row' },
    { name: 'Pull-up or lat pulldown', note: 'Assisted or banded counts.' },
  ],
  secondary: [
    { name: 'Seated cable row' },
    { name: 'Face pull', note: 'For the shoulders you cannot see in the mirror.' },
    { name: 'Dumbbell curl' },
    { name: 'Rear delt fly' },
  ],
};

const LEGS = {
  primary: [
    { name: 'Back squat', note: 'Goblet squat is a real substitute, not a lesser one.' },
    { name: 'Romanian deadlift', note: 'Hinge at the hip; the bar stays close.' },
  ],
  secondary: [
    { name: 'Split squat or lunge' },
    { name: 'Leg press or hack squat' },
    { name: 'Leg curl' },
    { name: 'Standing calf raise' },
  ],
};

const CORE = [
  { name: 'Plank', note: 'Time under tension, not a race.' },
  { name: 'Hanging knee raise' },
  { name: 'Cable or band woodchop' },
  { name: 'Dead bug' },
];

const FULL_BODY_PRIMARY = [
  { name: 'Goblet or back squat' },
  { name: 'Bench press or push-up' },
  { name: 'Barbell row or lat pulldown' },
];

const FULL_BODY_SECONDARY = [
  { name: 'Romanian deadlift' },
  { name: 'Overhead press' },
  { name: 'Plank' },
];

/* ─────────────────────────────────────────────────────────────────────────────
   Rep and volume prescription
   ───────────────────────────────────────────────────────────────────────────*/

/**
 * Rep ranges by focus.
 *
 * All three phases lift in broadly the same way, which surprises people: you do
 * not "lift for toning" on a cut. What changes is how much conditioning sits
 * around the lifting and how much total volume is sustainable. Cutting keeps the
 * loads so the strength built earlier is still there afterwards.
 */
function repScheme(focus: TrainingFocus, experience: Experience) {
  if (experience === 'beginner') {
    return { primary: '3 x 8', secondary: '3 x 10-12', note: 'Add a little weight when all sets feel controlled.' };
  }
  if (focus === 'bulking') {
    return { primary: '4 x 5-8', secondary: '3 x 8-12', note: 'Leave one or two reps in reserve on the last set.' };
  }
  if (focus === 'cutting') {
    return { primary: '4 x 5-6', secondary: '3 x 10-15', note: 'Keep the heavy sets heavy — that is what protects strength.' };
  }
  return { primary: '4 x 6-8', secondary: '3 x 10-12', note: 'Steady loads, steady effort.' };
}

/** How many movements fit honestly in the time available. */
function exerciseBudget(sessionMinutes: number): number {
  if (sessionMinutes <= 30) return 3;
  if (sessionMinutes <= 45) return 4;
  if (sessionMinutes <= 60) return 5;
  return 6;
}

type Pool = { name: string; note?: string };

function take(primary: Pool[], secondary: Pool[], budget: number, scheme: ReturnType<typeof repScheme>): PlanExercise[] {
  const out: PlanExercise[] = [];
  for (const p of primary) {
    if (out.length >= budget) break;
    const [sets, reps] = scheme.primary.split(' x ');
    out.push({ name: p.name, sets: Number(sets), reps, note: p.note });
  }
  for (const s of secondary) {
    if (out.length >= budget) break;
    const [sets, reps] = scheme.secondary.split(' x ');
    out.push({ name: s.name, sets: Number(sets), reps, note: s.note });
  }
  return out;
}

/* ─────────────────────────────────────────────────────────────────────────────
   The split
   ───────────────────────────────────────────────────────────────────────────*/

function buildDays(inputs: PlanInputs): { splitName: string; rationale: string; days: PlanDay[] } {
  const { experience, daysPerWeek, sessionMinutes, focus } = inputs;
  const scheme = repScheme(focus, experience);
  const budget = exerciseBudget(sessionMinutes);

  // A beginner, or anyone training twice a week, gets full-body. Hitting each
  // movement twice a week beats splitting it across days that do not exist.
  if (experience === 'beginner' || daysPerWeek <= 3) {
    const days: PlanDay[] = [];
    for (let i = 0; i < daysPerWeek; i++) {
      days.push({
        label: `Day ${i + 1}`,
        focus: 'Full body',
        exercises: take(
          // Rotate the order so the same lift is not always done last and tired.
          [...FULL_BODY_PRIMARY.slice(i % 3), ...FULL_BODY_PRIMARY.slice(0, i % 3)],
          FULL_BODY_SECONDARY,
          budget,
          scheme
        ),
      });
    }
    return {
      splitName: 'Full body',
      rationale:
        experience === 'beginner'
          ? 'Everything, every session. At this stage the fastest progress comes from practising the main movements often, not from splitting them up.'
          : 'Across two or three sessions a week, full body hits each movement more often than a split would.',
      days,
    };
  }

  if (daysPerWeek === 4) {
    const days: PlanDay[] = [
      { label: 'Day 1', focus: 'Upper', exercises: take(PUSH.primary, [...PUSH.secondary, ...PULL.secondary], budget, scheme) },
      { label: 'Day 2', focus: 'Lower', exercises: take(LEGS.primary, [...LEGS.secondary, ...CORE], budget, scheme) },
      { label: 'Day 3', focus: 'Upper', exercises: take(PULL.primary, [...PULL.secondary, ...PUSH.secondary], budget, scheme) },
      { label: 'Day 4', focus: 'Lower', exercises: take([LEGS.primary[1], LEGS.primary[0]], [...LEGS.secondary.slice(1), ...CORE], budget, scheme) },
    ];
    return {
      splitName: 'Upper / Lower',
      rationale: 'Four sessions splits cleanly in half, and each half comes round twice a week.',
      days,
    };
  }

  // 5-6 days: push / pull / legs, run through once or twice.
  const cycle: PlanDay[] = [
    { label: 'Push', focus: 'Chest, shoulders, triceps', exercises: take(PUSH.primary, PUSH.secondary, budget, scheme) },
    { label: 'Pull', focus: 'Back and biceps', exercises: take(PULL.primary, PULL.secondary, budget, scheme) },
    { label: 'Legs', focus: 'Quads, hamstrings, calves, core', exercises: take(LEGS.primary, [...LEGS.secondary, ...CORE], budget, scheme) },
  ];
  const days = Array.from({ length: daysPerWeek }, (_, i) => ({
    ...cycle[i % 3],
    label: `Day ${i + 1} — ${cycle[i % 3].label}`,
  }));
  return {
    splitName: 'Push / Pull / Legs',
    rationale: 'At five or six sessions there is room to give each region its own day and still recover.',
    days,
  };
}

/* ─────────────────────────────────────────────────────────────────────────────
   Conditioning, progression, food, and when to ask a human
   ───────────────────────────────────────────────────────────────────────────*/

function conditioningFor(focus: TrainingFocus, preference: Preference): string[] {
  const out: string[] = [];
  if (focus === 'cutting') {
    out.push('Two or three easy sessions a week — a brisk walk, the bike, or a class. Easy enough to hold a conversation.');
    out.push('Keep it away from your heaviest lifting day if you can, so the lifting stays strong.');
  } else if (focus === 'bulking') {
    out.push('One or two short easy sessions a week. Enough to keep your wind, not enough to eat into recovery.');
  } else {
    out.push('Two easy sessions a week, whatever you enjoy enough to keep doing.');
  }
  if (preference === 'classes') {
    out.push('Your classes count as the conditioning here — no need to add more on top.');
  } else if (preference === 'both') {
    out.push('A class can replace one of these entirely. Book it from the app.');
  }
  return out;
}

function progressionFor(experience: Experience, scheme: ReturnType<typeof repScheme>): string[] {
  const out = [scheme.note];
  if (experience === 'beginner') {
    out.push('Add weight to a lift once you can finish every set at the top of the rep range with clean form.');
    out.push('Log each session. Two weeks of numbers tells you more than how any single session felt.');
  } else {
    out.push('Aim to beat the previous session by a rep or a small jump in load — not both at once.');
    out.push('When a lift stalls three sessions running, drop about 10% and build back up.');
  }
  out.push('Take an easier week roughly every sixth week. Same sessions, lighter loads.');
  return out;
}

/**
 * General practice only. No targets, no numbers, nothing individual — see the
 * header for why this line is drawn where it is.
 */
function nutritionFor(focus: TrainingFocus): string[] {
  const shared = [
    'Get a protein source into every main meal — eggs, fish, chicken, tofu, beans, whatever you actually eat.',
    'Drink water across the day, and more of it on training days. Mamburao heat is part of your training load.',
    'Eat something with carbohydrate an hour or two before you train, so the session has fuel behind it.',
    'Sleep is the part of recovery no plan can replace.',
  ];
  if (focus === 'bulking') {
    return [
      'Eating a little more than usual is the point of this phase — spread it across meals rather than one large one.',
      ...shared,
    ];
  }
  if (focus === 'cutting') {
    return [
      'Keep protein and vegetables high while overall portions come down; that is what makes a cut feel manageable.',
      ...shared,
    ];
  }
  return shared;
}

function seeACoachFor(inputs: PlanInputs): string[] {
  const out: string[] = [];
  if (inputs.limitations.trim()) {
    // Deliberately does not modify the exercises. Programming around an injury
    // from a text box is exactly the thing a rule table must not attempt.
    out.push(
      'You mentioned something to work around. This plan has not been adjusted for it — bring it to a trainer before you start, and they will swap what needs swapping.'
    );
  }
  if (inputs.experience === 'beginner') {
    out.push('Book one session to have the squat, hinge, press and row watched. It is the highest-value hour a beginner can spend.');
  }
  out.push('If a movement hurts — sharp, not the usual effort — stop it and ask. Do not train through it.');
  out.push('For anything about food that is specific to you, your health or your medication, ask a qualified professional rather than an app.');
  return out;
}

/** Clamp the answers to what the generator can honestly programme for. */
export function normaliseInputs(raw: PlanInputs): PlanInputs {
  return {
    ...raw,
    daysPerWeek: Math.max(2, Math.min(6, Math.round(raw.daysPerWeek))),
    limitations: raw.limitations.trim(),
  };
}

export function buildPlan(raw: PlanInputs, now: Date = new Date()): PlanSpec {
  const inputs = normaliseInputs(raw);
  const scheme = repScheme(inputs.focus, inputs.experience);
  const { splitName, rationale, days } = buildDays(inputs);

  return {
    version: 1,
    builtAt: now.toISOString(),
    inputs,
    splitName,
    rationale,
    days,
    conditioning: conditioningFor(inputs.focus, inputs.preference),
    progression: progressionFor(inputs.experience, scheme),
    nutrition: nutritionFor(inputs.focus),
    seeACoach: seeACoachFor(inputs),
  };
}
