# Compiles CoreFitnessAdmin.exe -- the desktop icon that opens the dashboard.
#
# Uses csc.exe from the .NET Framework that is already part of Windows, so this
# needs nothing installed: no Visual Studio, no SDK, no npm package. Output is a
# single 82 KB file in this folder (mostly the icon), and by default a copy on
# the Desktop.
#
#   .\desktop\build-exe.ps1              # build + put it on the Desktop
#   .\desktop\build-exe.ps1 -NoDesktop   # build only
#
# Re-running is safe; it overwrites the same files.

param([switch]$NoDesktop)

$ErrorActionPreference = 'Stop'

$here   = Split-Path -Parent $MyInvocation.MyCommand.Path
$server = Join-Path $here 'serve.mjs'
$icon   = Join-Path $here 'core-fitness-admin.ico'
$source = Join-Path $here 'CoreFitnessAdmin.cs'
$exe    = Join-Path $here 'CoreFitnessAdmin.exe'

if (-not (Test-Path $server)) { throw "Missing serve.mjs beside this script: $server" }
if (-not (Test-Path $source)) { throw "Missing CoreFitnessAdmin.cs: $source" }
if (-not (Test-Path $icon))   { & (Join-Path $here 'make-icon.ps1') }

# csc.exe lives inside Windows. v4.0.30319 is the last (and current) Framework
# directory -- it has shipped in every Windows since 8, so this is not a gamble.
$csc = Join-Path $env:SystemRoot 'Microsoft.NET\Framework64\v4.0.30319\csc.exe'
if (-not (Test-Path $csc)) {
  $csc = Join-Path $env:SystemRoot 'Microsoft.NET\Framework\v4.0.30319\csc.exe'
}
if (-not (Test-Path $csc)) {
  throw "Cannot find csc.exe under $env:SystemRoot\Microsoft.NET. Enable .NET Framework 4.x in Windows Features."
}

# The .exe has to keep working after somebody copies it to the Desktop, where
# there is no serve.mjs beside it. So the real location is baked in here, at
# build time, as a last-resort fallback. A verbatim string: the path is full of
# backslashes and at least one space.
$serverFull = (Resolve-Path $server).Path
$generated  = Join-Path $here 'Installed.generated.cs'
@"
// GENERATED by build-exe.ps1 -- do not edit, do not commit assumptions about it.
// The absolute path recorded when this machine built the launcher, so that a
// copy of the .exe sitting on the Desktop can still find the server it starts.
// Assembly attributes must come before any type, or csc answers CS1730.
[assembly: System.Reflection.AssemblyTitle("Core Fitness Admin")]
[assembly: System.Reflection.AssemblyProduct("Core Fitness Gym Management")]
[assembly: System.Reflection.AssemblyDescription("Opens the Core Fitness admin dashboard")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]

internal static class Installed
{
    internal const string ServerPath = @"$serverFull";
}
"@ | Set-Content -Path $generated -Encoding utf8

$cscArgs = @(
  '/nologo',
  '/target:winexe',          # no console window -- the point of the whole exercise
  '/platform:anycpu',
  '/optimize+',
  "/win32icon:$icon",
  '/reference:System.Windows.Forms.dll',
  "/out:$exe",
  $source,
  $generated
)

& $csc $cscArgs
if ($LASTEXITCODE -ne 0) { throw "csc.exe failed with exit code $LASTEXITCODE" }
Remove-Item $generated -Force
Write-Output "built: $exe"

if (-not $NoDesktop) {
  $dest = Join-Path ([Environment]::GetFolderPath('Desktop')) 'Core Fitness Admin.exe'
  Copy-Item $exe $dest -Force
  Write-Output "copied: $dest"
}

$dist = Join-Path $here '..\dist\index.html'
if (-not (Test-Path $dist)) {
  Write-Warning "g-fitness-admin\dist is missing -- the .exe will offer to run 'npm run build' the first time it is opened."
}
