-- Removes everything seed-demo-data.sql and seed-demo-data-2.sql created —
-- and only that.
--
--     select remove_demo_data();
--
-- That is the whole script now. **The logic moved into migration 0117**, and
-- this file calls it rather than repeating it: two copies of a delete this
-- wide is how one copy gets a fix and the other does not, and the stale one is
-- what somebody pastes the evening before a demo.
--
-- You do not need to paste anything at all any more. The platform app
-- (localhost) has it on its Platform screen, with the counts beside it and a
-- typed confirmation — which is the point, because this cannot be undone.
-- This file is here for a terminal, a broken UI, or a `psql` session.
--
-- Platform admin only. A gym owner can *see* how much of their dashboard is
-- seeded (admin → System), because a gym whose figures are inflated is
-- entitled to know; removing it reaches outside any one gym and is not theirs
-- to press.
--
-- ## What it does, unchanged since it was a paste
--
-- Demo **people** are those whose id matches `5eed____-0000-4000-8000-…` **and**
-- whose email ends `@seed.corefitness-test.com` — both, not either. Everything
-- else goes by person as well as by id pattern, so a payment recorded against a
-- demo member during a demo goes too, even though its id was random.
--
-- Three things a demo may have done, all handled:
--
--   * **A retired demo template reactivated**, generating real bookable classes
--     a real member may have booked. Those go with the template: the class was
--     never real.
--   * **A demo reward redeemed by a real member.** The redemption goes, or the
--     reward could not be deleted. Their points are untouched — redemptions are
--     recorded against the ledger, not taken out of it.
--   * **A real class given to a demo coach.** The class stays; it just has no
--     coach again.
--
-- Triggers are disabled inside the transaction while it runs, because deleting
-- fires them and every removed booking, payment and redemption would otherwise
-- write an audit entry or a notification about somebody who never existed.
--
-- Safe to run twice, and safe if only part 1 was ever run: with nothing to
-- remove it says so and changes nothing.

select remove_demo_data();
