-- 0047 — the generated training plan, kept.
--
-- `buildPlan()` is deterministic, so in principle the plan could be regenerated
-- from the answers every time and never stored. It is stored anyway, for two
-- reasons that both matter more than the disk space:
--
--  1. **The rules will change.** When the exercise pool or the rep scheme is
--     edited, a member's plan would silently rewrite itself underneath them —
--     the programme they had been following for three weeks quietly becomes a
--     different programme. Storing the output pins it until they rebuild.
--  2. **A coach needs to see what the member is actually doing**, not what the
--     current version of the generator would produce today.
--
-- ---------------------------------------------------------------------------
-- Why the spec and not the prose
-- ---------------------------------------------------------------------------
-- `spec` holds the structured PlanSpec — split, days, exercises, sets, reps —
-- not the rendered text. The wording lives in `planRender.ts` and is applied at
-- display time.
--
-- That is what keeps the door open for the hybrid the gym may want later: a
-- model that rewords the plan conversationally replaces the renderer only, so
-- the sets and reps stay generated by auditable rules and the model never gets
-- to invent a number. An old plan then re-renders in the new voice without a
-- backfill, because what was stored was the facts.
--
-- `version` inside the JSON says which shape it is, so a future PlanSpec v2 can
-- be told apart from v1 rather than guessed at.
--
-- ---------------------------------------------------------------------------
-- History, not a single row
-- ---------------------------------------------------------------------------
-- One row per build, newest is current. A member who rebuilds after switching
-- from bulking to cutting can still see what they were doing before, and the
-- gym can see that a plan changed - which is the sort of thing that gets
-- argued about at a front desk.

create table if not exists workout_plans (
  id         uuid primary key default gen_random_uuid(),
  member_id  uuid not null references member_profiles(profile_id) on delete cascade,
  spec       jsonb not null,
  created_at timestamptz not null default now()
);

comment on table workout_plans is
  'Generated training plans, newest first. `spec` is the structured PlanSpec '
  'from utils/planBuilder.ts - the facts, not the wording - so the rendering '
  'can change (including to a model-worded one) without rewriting history.';

comment on column workout_plans.spec is
  'PlanSpec JSON. Carries its own `version` so a later shape is distinguishable.';

-- The only query this table has: give me this member's plans, newest first.
create index if not exists idx_workout_plans_member
  on workout_plans (member_id, created_at desc);

-- A plan must at least say which shape it is; a spec with no version is a bug
-- that would otherwise sit in the table until something tried to render it.
alter table workout_plans drop constraint if exists workout_plans_spec_versioned;
alter table workout_plans
  add constraint workout_plans_spec_versioned
    check (spec ? 'version')
    not valid;

alter table workout_plans enable row level security;

-- The member owns their plans outright.
drop policy if exists workout_plans_all_self on workout_plans;
create policy workout_plans_all_self on workout_plans
  for all
  using (member_id = auth.uid())
  with check (member_id = auth.uid());

-- The gym reads them under the sharing switch the member already controls
-- (0032). A training plan is a workout thing, so it reuses the 'workouts'
-- category rather than inventing a fourth switch nobody asked for: a member who
-- has already said "my coach may see my workouts" has answered this question.
--
-- Read-only on purpose. A trainer who wants to change the programme should be
-- writing it with the member, not editing a generated row behind them.
drop policy if exists workout_plans_select_gym on workout_plans;
create policy workout_plans_select_gym on workout_plans
  for select
  using (trainer_may_see(member_id, 'workouts'));
