-- 0085 — a trainer describes and runs their own classes.
--
-- 0071 let a trainer change one number on a class they teach: its size. The
-- name, the level, the room and the time were the gym's alone, so a coach who
-- wanted "Beginner Kettlebells, Thursday 6 PM, 8 places" had to ask the desk,
-- and a class's details could not be corrected by the person teaching it
-- (the gym's request, 2026-09-18).
--
-- ## What a trainer may now do — always on their own classes only
--
--   * **Create** a one-off class taught by themselves, in the future, at a time
--     they are free (the same `assert_trainer_free` 0068 uses for 1-on-1).
--   * **Edit** the name, level, size and room of any class they teach.
--   * **Move** the time or length only of a class they created (no template).
--     A class generated from the gym's timetable keeps the gym's time: moving
--     one occurrence would make it disagree with the template it came from.
--   * **Delete** a class they created, while nobody is booked into it.
--
-- ## What stays the gym's
--
--   * Who teaches a class — a trainer cannot hand a class to a colleague or
--     take one over; `trainer_id` is pinned to themselves.
--   * The timetable templates (`class_templates`), which still only the desk
--     writes (0015).
--   * The size floor from 0071: never below the members already booked in.
--
-- A policy chooses rows, never columns, so the column rules live in the guard
-- trigger below, as 0071's did. The desk (admin, staff) is untouched by it.

-- ── Create: a trainer's own one-off class ───────────────────────────────────
drop policy if exists classes_insert_trainer on classes;
create policy classes_insert_trainer on classes for insert
  to authenticated
  with check (
    get_my_role() = 'trainer'
    and trainer_id = auth.uid()
    and template_id is null
  );

-- ── Delete: a class they created, with nobody in it ────────────────────────
drop policy if exists classes_delete_trainer on classes;
create policy classes_delete_trainer on classes for delete
  to authenticated
  using (
    get_my_role() = 'trainer'
    and trainer_id = auth.uid()
    and template_id is null
    and not exists (
      select 1 from bookings b
       where b.class_id = classes.id and b.status in ('pending', 'approved')
    )
  );

-- ── The column rules, for inserts and updates by a trainer ─────────────────
create or replace function trg_trainer_class_edit_guard() returns trigger
language plpgsql security definer set search_path = public as $fn$
declare
  v_role text;
begin
  select role::text into v_role from profiles where id = auth.uid();
  if v_role is distinct from 'trainer' then
    return new;   -- the desk may edit anything; this guard is about trainers
  end if;

  if tg_op = 'INSERT' then
    if new.trainer_id is distinct from auth.uid() then
      raise exception 'A trainer can only create classes they teach themselves.';
    end if;
    if new.template_id is not null then
      raise exception 'Timetable classes are generated by the gym.';
    end if;
    if new.scheduled_at is null or new.scheduled_at <= now() then
      raise exception 'Pick a time that has not passed yet.';
    end if;
    if new.capacity is null or new.capacity < 1 then
      raise exception 'A class needs room for at least one person.';
    end if;
    perform assert_trainer_free(
      new.trainer_id, new.scheduled_at,
      new.scheduled_at + make_interval(mins => new.duration_minutes),
      'class', new.id);
    return new;
  end if;

  -- UPDATE
  if new.trainer_id is distinct from old.trainer_id then
    raise exception 'Who teaches a class is set by the gym.';
  end if;
  if new.template_id is distinct from old.template_id then
    raise exception 'Timetable classes are generated by the gym.';
  end if;

  if new.scheduled_at is distinct from old.scheduled_at
     or new.duration_minutes is distinct from old.duration_minutes then
    if old.template_id is not null then
      raise exception
        'This class comes from the gym''s weekly timetable, so its time is set by the gym. You can still change its name, level, size and room.';
    end if;
    if new.scheduled_at is null or new.scheduled_at <= now() then
      raise exception 'Pick a time that has not passed yet.';
    end if;
    perform assert_trainer_free(
      new.trainer_id, new.scheduled_at,
      new.scheduled_at + make_interval(mins => new.duration_minutes),
      'class', new.id);
  end if;

  -- Never below the seats already taken (0071): those members are booked in,
  -- and a capacity under the roster makes every "spots left" reading negative.
  if new.capacity < (
    select count(*) from bookings b
     where b.class_id = new.id and b.status in ('pending', 'approved')
  ) then
    raise exception 'That class already has more members booked than the size you set.';
  end if;
  if new.capacity < 1 then
    raise exception 'A class needs room for at least one person.';
  end if;

  return new;
end;
$fn$;

drop trigger if exists trainer_class_edit_guard on classes;
create trigger trainer_class_edit_guard
  before insert or update on classes
  for each row execute function trg_trainer_class_edit_guard();

-- 0071's update policy is unchanged: a trainer's own rows, and they must stay
-- their own.
drop policy if exists classes_update_trainer on classes;
create policy classes_update_trainer on classes for update
  using (trainer_id = auth.uid())
  with check (trainer_id = auth.uid());

-- Marker for scripts/probe-migrations.py.
create or replace function migration_0085_applied() returns boolean
language sql immutable as $fn$ select true $fn$;

revoke all on function migration_0085_applied() from public, anon;
grant execute on function migration_0085_applied() to authenticated;

comment on function migration_0085_applied() is
  'Marker for scripts/probe-migrations.py. Delete only alongside the probe entry.';

-- VERIFICATION — as a real trainer (set request.jwt.claim.sub), not the owner:
--   insert into classes (name, trainer_id, level, capacity, scheduled_at, duration_minutes)
--     values ('Kettlebells', auth.uid(), 'beginner', 8, now() + interval '2 days', 60);  -- ok
--   the same with trainer_id = '<a colleague>'                                         -- refused
--   update classes set level = 'advanced' where id = '<a timetable class I teach>';    -- ok
--   update classes set scheduled_at = scheduled_at + interval '1 hour'
--    where id = '<a timetable class I teach>';                                         -- refused
--   delete from classes where id = '<my one-off with a booking>';                      -- 0 rows
