-- 0126: THE FULL EXERCISE LIBRARY
--
-- 0050 seeded 36 movements. A gym opening today needs the rest of the floor:
-- this adds 193 more to the shared library (gym_id NULL), which every gym reads,
-- so 229 in all, each with starter cues and steps in the same plain coaching
-- language as 0121 (a cue is what a coach says across the floor; no medical
-- claims).
--
-- Rules it keeps:
--   * the shared library is the platform's (0121) — rows land with gym_id NULL,
--     created_by NULL, exactly like 0050's;
--   * a name already in the library is skipped, never overwritten, so a re-run
--     changes nothing and the platform's later edits survive;
--   * a gym that already made its OWN exercise with one of these names keeps
--     its own, and the new shared one is hidden for that gym only (the 0121
--     overlay) — otherwise its members would see the name twice and split their
--     history between two rows.
--
-- Equipment stays within the six values the screens offer; kettlebells, bands,
-- medicine balls and sleds are 'other', a Smith machine is 'machine'.

insert into exercises (gym_id, name, muscle_group, equipment, is_timed, sort_order, cues, steps, created_by)
select null, v.name, v.grp, v.equip, v.timed, v.ord, v.cues, v.steps, null
from (values
  ('Incline Barbell Bench Press', 'chest', 'barbell', false, 101,
   array['Bench at 30 to 45 degrees', 'Bar touches upper chest', 'Shoulder blades pinched']::text[],
   array['Lie on the incline bench with eyes under the bar.', 'Grip just wider than shoulders and unrack.', 'Lower the bar to your upper chest under control.', 'Press it back up over your shoulders.']::text[]),
  ('Decline Barbell Bench Press', 'chest', 'barbell', false, 102,
   array['Legs locked under the pads', 'Bar to lower chest', 'Use a spotter']::text[],
   array['Hook your legs under the pads and lie back.', 'Unrack with a grip just wider than shoulders.', 'Lower the bar to your lower chest.', 'Press it back up in a straight line.']::text[]),
  ('Close-Grip Bench Press', 'chest', 'barbell', false, 103,
   array['Hands about shoulder-width', 'Elbows close to the body', 'Bar to lower chest']::text[],
   array['Lie on the bench and grip the bar at shoulder width.', 'Unrack and hold it over your shoulders.', 'Lower it to your lower chest, elbows tucked.', 'Press up until your arms are straight.']::text[]),
  ('Dumbbell Bench Press', 'chest', 'dumbbell', false, 104,
   array['Feet flat, back arched slightly', 'Dumbbells level', 'Press up and slightly in']::text[],
   array['Sit with dumbbells on your thighs, then lie back and bring them to your chest.', 'Press both up until your arms are straight.', 'Lower slowly until they are beside your chest.', 'Press back up.']::text[]),
  ('Decline Dumbbell Press', 'chest', 'dumbbell', false, 105,
   array['Legs secured', 'Control the dumbbells', 'Lower to the lower chest']::text[],
   array['Hook your legs in and lie back with a dumbbell in each hand.', 'Press them up over your chest.', 'Lower them to the sides of your lower chest.', 'Press back up.']::text[]),
  ('Dumbbell Fly', 'chest', 'dumbbell', false, 106,
   array['Soft bend in the elbows', 'Wide arc, like hugging a tree', 'Stop at a comfortable stretch']::text[],
   array['Lie on a flat bench holding dumbbells over your chest, palms facing.', 'Open your arms out wide with a slight elbow bend.', 'Stop when you feel a stretch across your chest.', 'Bring them back together over your chest.']::text[]),
  ('Incline Dumbbell Fly', 'chest', 'dumbbell', false, 107,
   array['Bench at about 30 degrees', 'Elbows stay slightly bent', 'Squeeze at the top']::text[],
   array['Lie on the incline holding dumbbells above your chest.', 'Lower them out to the sides in a wide arc.', 'Stop at a comfortable stretch.', 'Bring them back up together.']::text[]),
  ('Cable Crossover', 'chest', 'cable', false, 108,
   array['Slight forward lean', 'Hands meet in front of the chest', 'Slow on the way back']::text[],
   array['Set both pulleys high and hold a handle in each hand.', 'Step forward with one foot and lean slightly.', 'Bring your hands down and together in front of you.', 'Let them return slowly until you feel a stretch.']::text[]),
  ('Low-to-High Cable Fly', 'chest', 'cable', false, 109,
   array['Pulleys low', 'Scoop up to chin height', 'Squeeze the upper chest']::text[],
   array['Set both pulleys at the bottom and hold a handle in each hand.', 'Stand in the middle with a slight elbow bend.', 'Sweep your hands up and together to chin height.', 'Lower them slowly.']::text[]),
  ('Machine Chest Press', 'chest', 'machine', false, 110,
   array['Handles at mid-chest', 'Back flat on the pad', 'Do not lock the elbows']::text[],
   array['Set the seat so the handles line up with your mid-chest.', 'Grip the handles and press them forward.', 'Stop just short of locking your elbows.', 'Return slowly.']::text[]),
  ('Pec Deck', 'chest', 'machine', false, 111,
   array['Elbows at shoulder height', 'Squeeze the chest, not the arms', 'Slow return']::text[],
   array['Sit with your back flat and arms on the pads or handles.', 'Bring your arms together in front of your chest.', 'Squeeze for a moment.', 'Return slowly until you feel a stretch.']::text[]),
  ('Smith Machine Bench Press', 'chest', 'machine', false, 112,
   array['Bar over mid-chest', 'Set the safety stops', 'Controlled tempo']::text[],
   array['Set the bench so the bar lowers to your mid-chest.', 'Grip just wider than shoulders and unhook the bar.', 'Lower it to your chest.', 'Press it back up and re-hook it at the end.']::text[]),
  ('Incline Push-up', 'chest', 'bodyweight', false, 113,
   array['Hands on a bench or box', 'Body in a straight line', 'Chest to the edge']::text[],
   array['Place your hands on a bench, shoulder-width apart.', 'Walk your feet back into a straight plank.', 'Lower your chest to the bench.', 'Push back up.']::text[]),
  ('Decline Push-up', 'chest', 'bodyweight', false, 114,
   array['Feet on a bench', 'Keep hips level', 'Chest toward the floor']::text[],
   array['Put your feet on a bench and hands on the floor.', 'Hold your body in a straight line.', 'Lower your chest toward the floor.', 'Push back up.']::text[]),
  ('Wide Push-up', 'chest', 'bodyweight', false, 115,
   array['Hands wider than shoulders', 'Straight body line', 'Full range']::text[],
   array['Start in a plank with hands wider than your shoulders.', 'Lower your chest toward the floor.', 'Push back up to straight arms.']::text[]),
  ('Diamond Push-up', 'arms', 'bodyweight', false, 501,
   array['Hands together under the chest', 'Elbows close to the body', 'Straight body line']::text[],
   array['Start in a plank with hands together, thumbs and fingers touching.', 'Lower your chest to your hands.', 'Push back up, keeping elbows tucked.']::text[]),
  ('Knee Push-up', 'chest', 'bodyweight', false, 116,
   array['Straight line knees to head', 'Hands under shoulders', 'Chest to the floor']::text[],
   array['Kneel and place your hands under your shoulders.', 'Lean forward so your body is straight from knees to head.', 'Lower your chest toward the floor.', 'Push back up.']::text[]),
  ('Chest Dip', 'chest', 'bodyweight', false, 117,
   array['Lean forward', 'Elbows slightly out', 'Lower to a comfortable depth']::text[],
   array['Support yourself on the dip bars with straight arms.', 'Lean your torso forward.', 'Bend your elbows to lower your chest.', 'Push back up.']::text[]),
  ('Dumbbell Pullover', 'chest', 'dumbbell', false, 118,
   array['Hips slightly low', 'Arms nearly straight', 'Feel the stretch through the chest and lats']::text[],
   array['Lie across or along a bench holding one dumbbell over your chest with both hands.', 'Lower it back over your head with a slight elbow bend.', 'Stop at a comfortable stretch.', 'Pull it back over your chest.']::text[]),
  ('Svend Press', 'chest', 'other', false, 119,
   array['Squeeze the plates together', 'Press straight out', 'Keep squeezing the whole time']::text[],
   array['Hold two small plates pressed together at your chest.', 'Push them straight out in front of you, squeezing hard.', 'Bring them back to your chest.']::text[]),
  ('Landmine Press', 'chest', 'barbell', false, 120,
   array['Bar end at the shoulder', 'Press up and forward', 'Brace your core']::text[],
   array['Set one end of a bar in a landmine or corner.', 'Hold the other end at your shoulder.', 'Press it up and forward until your arm is straight.', 'Lower it back to your shoulder.']::text[]),
  ('Chin-up', 'back', 'bodyweight', false, 201,
   array['Palms facing you', 'Chest to the bar', 'Full hang at the bottom']::text[],
   array['Hang from the bar with palms facing you, shoulder-width.', 'Pull until your chin clears the bar.', 'Lower all the way down under control.']::text[]),
  ('Neutral-Grip Pull-up', 'back', 'bodyweight', false, 202,
   array['Palms facing each other', 'Shoulders down first', 'No swinging']::text[],
   array['Hang from parallel handles, palms facing each other.', 'Pull your shoulders down, then pull up.', 'Get your chin over the handles.', 'Lower slowly.']::text[]),
  ('Assisted Pull-up', 'back', 'machine', false, 203,
   array['Kneel or stand on the pad', 'Pull chest toward the bar', 'Control the descent']::text[],
   array['Set the assistance weight and kneel on the pad.', 'Grip the bar just wider than shoulders.', 'Pull until your chin passes the bar.', 'Lower slowly to straight arms.']::text[]),
  ('Inverted Row', 'back', 'bodyweight', false, 204,
   array['Body straight as a plank', 'Pull chest to the bar', 'Squeeze shoulder blades']::text[],
   array['Lie under a bar set at hip height and grip it.', 'Straighten your body with heels on the floor.', 'Pull your chest to the bar.', 'Lower until your arms are straight.']::text[]),
  ('Single-Arm Dumbbell Row', 'back', 'dumbbell', false, 205,
   array['Flat back', 'Pull toward the hip', 'Do not twist']::text[],
   array['Put one knee and hand on a bench, dumbbell in the other hand.', 'Let the dumbbell hang with a flat back.', 'Row it up toward your hip.', 'Lower it under control.']::text[]),
  ('Chest-Supported Dumbbell Row', 'back', 'dumbbell', false, 206,
   array['Chest stays on the pad', 'Elbows back', 'Squeeze at the top']::text[],
   array['Lie face down on an incline bench with a dumbbell in each hand.', 'Let your arms hang straight.', 'Row both dumbbells up, elbows back.', 'Lower slowly.']::text[]),
  ('Pendlay Row', 'back', 'barbell', false, 207,
   array['Torso parallel to the floor', 'Bar starts on the floor each rep', 'Explosive pull']::text[],
   array['Hinge over the bar with a flat back, torso near parallel.', 'Grip just wider than shoulders.', 'Pull the bar quickly to your lower chest.', 'Set it back down on the floor.']::text[]),
  ('T-Bar Row', 'back', 'barbell', false, 208,
   array['Hinge with a flat back', 'Pull to the chest', 'No bouncing']::text[],
   array['Straddle the bar and hold the handle.', 'Hinge forward with a flat back and soft knees.', 'Row the handle to your chest.', 'Lower it under control.']::text[]),
  ('Meadows Row', 'back', 'barbell', false, 209,
   array['Staggered stance', 'Pull elbow high and back', 'Control the stretch']::text[],
   array['Stand beside a landmine bar end in a staggered stance.', 'Grip the bar end with one hand.', 'Row it up, elbow high and back.', 'Lower it slowly.']::text[]),
  ('Machine Row', 'back', 'machine', false, 210,
   array['Chest against the pad', 'Pull elbows back', 'Pause and squeeze']::text[],
   array['Set the seat so the handles are at chest height.', 'Hold the handles with straight arms.', 'Pull them back, squeezing your shoulder blades.', 'Return slowly.']::text[]),
  ('Close-Grip Lat Pulldown', 'back', 'cable', false, 211,
   array['Lean back slightly', 'Pull handle to upper chest', 'Elbows down and back']::text[],
   array['Attach a close-grip handle and sit under the pad.', 'Pull the handle to your upper chest.', 'Let it rise slowly until your arms are straight.']::text[]),
  ('Straight-Arm Pulldown', 'back', 'cable', false, 212,
   array['Arms stay straight', 'Hinge slightly forward', 'Pull to the thighs']::text[],
   array['Stand facing a high cable holding a bar or rope.', 'Hinge slightly with arms straight.', 'Sweep the bar down to your thighs.', 'Let it rise slowly.']::text[]),
  ('Single-Arm Cable Row', 'back', 'cable', false, 213,
   array['Tall posture', 'Pull to the hip', 'Slight reach forward at the start']::text[],
   array['Hold a cable handle in one hand at chest height.', 'Stand or sit tall.', 'Pull the handle to your side.', 'Return slowly with a slight reach.']::text[]),
  ('Rack Pull', 'back', 'barbell', false, 214,
   array['Bar just below the knees', 'Flat back', 'Lock out with the hips']::text[],
   array['Set the bar on safety pins just below your knees.', 'Grip it just outside your legs.', 'Stand up by driving your hips forward.', 'Lower it back to the pins.']::text[]),
  ('Sumo Deadlift', 'legs', 'barbell', false, 301,
   array['Wide stance, toes out', 'Hands inside the knees', 'Chest up, push the floor apart']::text[],
   array['Stand wide with toes out and the bar over mid-foot.', 'Grip the bar inside your knees.', 'Brace and push the floor away to stand.', 'Lower it back the same way.']::text[]),
  ('Trap Bar Deadlift', 'legs', 'barbell', false, 302,
   array['Stand in the middle', 'Chest up', 'Drive through the floor']::text[],
   array['Stand inside the trap bar and grip the handles.', 'Sit your hips down with a flat back.', 'Stand up by pushing the floor away.', 'Lower it back under control.']::text[]),
  ('Good Morning', 'back', 'barbell', false, 215,
   array['Soft knees', 'Hips go back', 'Back stays flat']::text[],
   array['Rest a light bar on your upper back.', 'Push your hips back, keeping your back flat.', 'Lower your chest until you feel a hamstring stretch.', 'Stand back up.']::text[]),
  ('Back Extension', 'back', 'machine', false, 216,
   array['Hips on the pad edge', 'Move from the hips', 'Do not overarch at the top']::text[],
   array['Set the pad just below your hips and hook your feet.', 'Cross your arms and lower your upper body.', 'Raise it until your body is straight.']::text[]),
  ('Superman', 'back', 'bodyweight', false, 217,
   array['Lift arms and legs together', 'Look at the floor', 'Pause at the top']::text[],
   array['Lie face down with arms stretched overhead.', 'Lift your arms, chest and legs off the floor.', 'Hold for a moment.', 'Lower slowly.']::text[]),
  ('Barbell Shrug', 'back', 'barbell', false, 218,
   array['Shoulders straight up', 'No rolling', 'Pause at the top']::text[],
   array['Hold the bar at your thighs with straight arms.', 'Lift your shoulders toward your ears.', 'Pause, then lower slowly.']::text[]),
  ('Dumbbell Shrug', 'back', 'dumbbell', false, 219,
   array['Arms stay straight', 'Shoulders to ears', 'Slow down']::text[],
   array['Hold a dumbbell in each hand at your sides.', 'Raise your shoulders straight up.', 'Pause and lower.']::text[]),
  ('Reverse Fly', 'shoulders', 'dumbbell', false, 401,
   array['Hinge forward', 'Arms out wide', 'Squeeze the upper back']::text[],
   array['Hinge forward holding light dumbbells under your chest.', 'Raise your arms out to the sides with a slight elbow bend.', 'Squeeze your shoulder blades.', 'Lower slowly.']::text[]),
  ('Reverse Pec Deck', 'shoulders', 'machine', false, 402,
   array['Chest against the pad', 'Arms wide', 'Lead with the elbows']::text[],
   array['Sit facing the pad and hold the handles in front of you.', 'Open your arms out and back.', 'Pause, then return slowly.']::text[]),
  ('Goblet Squat', 'legs', 'dumbbell', false, 303,
   array['Hold the weight at your chest', 'Elbows inside the knees', 'Sit down tall']::text[],
   array['Hold a dumbbell or kettlebell at your chest.', 'Stand with feet a little wider than shoulders.', 'Squat down keeping your chest up.', 'Stand back up.']::text[]),
  ('Bodyweight Squat', 'legs', 'bodyweight', false, 304,
   array['Weight in the whole foot', 'Knees follow toes', 'Chest up']::text[],
   array['Stand with feet shoulder-width apart.', 'Reach your arms forward and sit down and back.', 'Go as low as you comfortably can.', 'Stand back up.']::text[]),
  ('Box Squat', 'legs', 'barbell', false, 305,
   array['Sit back to the box', 'Pause without relaxing', 'Drive up']::text[],
   array['Set a box behind you at about knee height.', 'Squat back until you sit lightly on it.', 'Stay tight, then stand up.']::text[]),
  ('Hack Squat', 'legs', 'machine', false, 306,
   array['Back flat on the pad', 'Feet shoulder-width', 'Knees track over toes']::text[],
   array['Stand in the machine with shoulders under the pads.', 'Release the handles.', 'Lower until your knees are about 90 degrees.', 'Press back up.']::text[]),
  ('Smith Machine Squat', 'legs', 'machine', false, 307,
   array['Feet slightly forward', 'Chest up', 'Controlled descent']::text[],
   array['Set the bar on your upper back and unhook it.', 'Place your feet slightly in front of you.', 'Squat down.', 'Stand up and re-hook the bar at the end.']::text[]),
  ('Pendulum Squat', 'legs', 'machine', false, 308,
   array['Back on the pad', 'Deep, controlled reps', 'Push through the whole foot']::text[],
   array['Step into the machine with shoulders under the pads.', 'Release the lock.', 'Squat deep under control.', 'Press back up.']::text[]),
  ('Bulgarian Split Squat', 'legs', 'dumbbell', false, 309,
   array['Back foot on a bench', 'Front knee over the ankle', 'Drop straight down']::text[],
   array['Stand in front of a bench and rest one foot on it behind you.', 'Hold dumbbells at your sides.', 'Lower until your back knee nears the floor.', 'Push through the front foot to stand. Switch legs.']::text[]),
  ('Split Squat', 'legs', 'bodyweight', false, 310,
   array['Long stance', 'Torso upright', 'Back knee toward the floor']::text[],
   array['Take a long step forward and stay there.', 'Lower straight down until both knees bend.', 'Push back up. Finish one side, then switch.']::text[]),
  ('Reverse Lunge', 'legs', 'dumbbell', false, 311,
   array['Step back, not sideways', 'Front knee stable', 'Tall chest']::text[],
   array['Stand tall holding dumbbells.', 'Step one foot back and lower both knees.', 'Push through the front foot to return.', 'Alternate legs.']::text[]),
  ('Forward Lunge', 'legs', 'bodyweight', false, 312,
   array['Big step forward', 'Back knee toward the floor', 'Push back strongly']::text[],
   array['Stand tall with feet together.', 'Step forward and lower until both knees bend.', 'Push off the front foot to return.', 'Alternate legs.']::text[]),
  ('Lateral Lunge', 'legs', 'bodyweight', false, 313,
   array['Step wide to the side', 'Sit into one hip', 'Other leg stays straight']::text[],
   array['Stand with feet together.', 'Step wide to one side and sit your hips back over that foot.', 'Keep the other leg straight.', 'Push back to the start and switch sides.']::text[]),
  ('Curtsy Lunge', 'legs', 'bodyweight', false, 314,
   array['Step back and across', 'Hips face forward', 'Control the knee']::text[],
   array['Stand tall.', 'Step one foot behind and across the other.', 'Lower until both knees bend.', 'Return and switch sides.']::text[]),
  ('Step-up', 'legs', 'dumbbell', false, 315,
   array['Whole foot on the box', 'Drive through the top leg', 'Step down slowly']::text[],
   array['Stand facing a box holding dumbbells.', 'Put one whole foot on the box.', 'Push through it to stand on top.', 'Step down under control and repeat.']::text[]),
  ('Barbell Hip Thrust', 'legs', 'barbell', false, 316,
   array['Upper back on the bench', 'Chin tucked', 'Squeeze glutes at the top']::text[],
   array['Sit with your upper back against a bench and a padded bar over your hips.', 'Plant your feet about hip-width.', 'Drive your hips up until your body is flat.', 'Lower slowly.']::text[]),
  ('Glute Bridge', 'legs', 'bodyweight', false, 317,
   array['Heels close to the hips', 'Push through the heels', 'Squeeze at the top']::text[],
   array['Lie on your back with knees bent and feet flat.', 'Push through your heels to lift your hips.', 'Squeeze your glutes at the top.', 'Lower slowly.']::text[]),
  ('Single-Leg Glute Bridge', 'legs', 'bodyweight', false, 318,
   array['Hips stay level', 'One heel drives', 'Pause at the top']::text[],
   array['Lie on your back with one foot flat and the other leg raised.', 'Push through the planted heel to lift your hips.', 'Pause, then lower. Switch legs.']::text[]),
  ('Cable Kickback', 'legs', 'cable', false, 319,
   array['Hinge slightly', 'Kick straight back', 'Squeeze the glute']::text[],
   array['Attach an ankle strap to a low cable.', 'Hold the machine and hinge slightly.', 'Kick the leg straight back.', 'Return slowly. Switch legs.']::text[]),
  ('Hip Abduction Machine', 'legs', 'machine', false, 320,
   array['Sit tall', 'Push knees apart', 'Slow return']::text[],
   array['Sit with the pads on the outside of your knees.', 'Push your knees apart.', 'Return slowly.']::text[]),
  ('Hip Adduction Machine', 'legs', 'machine', false, 321,
   array['Sit tall', 'Squeeze knees together', 'Control the stretch']::text[],
   array['Sit with the pads on the inside of your knees.', 'Squeeze your legs together.', 'Return slowly.']::text[]),
  ('Seated Leg Curl', 'legs', 'machine', false, 322,
   array['Thigh pad snug', 'Curl fully', 'Slow on the way up']::text[],
   array['Sit with the pad above your heels and the thigh pad locked.', 'Curl your heels down and back.', 'Return slowly.']::text[]),
  ('Nordic Hamstring Curl', 'legs', 'bodyweight', false, 323,
   array['Anchor the heels', 'Lower as slowly as you can', 'Use your hands to catch']::text[],
   array['Kneel with your heels held down by a partner or pad.', 'Lower your body forward as slowly as you can.', 'Catch yourself with your hands.', 'Push back up and repeat.']::text[]),
  ('Stiff-Leg Deadlift', 'legs', 'barbell', false, 324,
   array['Legs nearly straight', 'Hips back', 'Flat back']::text[],
   array['Stand holding the bar at your thighs.', 'Keep your legs nearly straight and push your hips back.', 'Lower until you feel a hamstring stretch.', 'Stand back up.']::text[]),
  ('Dumbbell Romanian Deadlift', 'legs', 'dumbbell', false, 325,
   array['Soft knees', 'Dumbbells close to the legs', 'Hips back']::text[],
   array['Hold dumbbells in front of your thighs.', 'Push your hips back with a slight knee bend.', 'Lower until you feel a hamstring stretch.', 'Stand up by squeezing your glutes.']::text[]),
  ('Single-Leg Romanian Deadlift', 'legs', 'dumbbell', false, 326,
   array['Hips square', 'Back leg in line with the body', 'Slow and balanced']::text[],
   array['Hold a dumbbell and stand on one leg.', 'Hinge forward as the free leg reaches back.', 'Lower until your body is near parallel.', 'Return to standing. Switch legs.']::text[]),
  ('Seated Calf Raise', 'legs', 'machine', false, 327,
   array['Pad on the lower thighs', 'Full stretch', 'Pause at the top']::text[],
   array['Sit with the balls of your feet on the platform and the pad on your thighs.', 'Lower your heels for a stretch.', 'Push up as high as you can.', 'Lower slowly.']::text[]),
  ('Standing Calf Raise', 'legs', 'bodyweight', false, 328,
   array['Straight knees', 'Rise high', 'Slow lower']::text[],
   array['Stand on a step with your heels hanging off.', 'Rise onto your toes.', 'Lower your heels below the step.', 'Repeat.']::text[]),
  ('Wall Sit', 'legs', 'bodyweight', true, 329,
   array['Back flat on the wall', 'Knees at 90 degrees', 'Keep breathing']::text[],
   array['Lean against a wall and slide down.', 'Stop when your knees are about 90 degrees.', 'Hold for the time set.']::text[]),
  ('Jump Squat', 'legs', 'bodyweight', false, 330,
   array['Land softly', 'Knees follow toes', 'Explode up']::text[],
   array['Stand with feet shoulder-width.', 'Squat down.', 'Jump up as high as you can.', 'Land softly and go straight into the next rep.']::text[]),
  ('Box Jump', 'legs', 'other', false, 331,
   array['Swing the arms', 'Land softly on the whole foot', 'Step down, do not jump down']::text[],
   array['Stand facing a sturdy box.', 'Dip and swing your arms back.', 'Jump onto the box and land softly.', 'Stand tall, then step down.']::text[]),
  ('Sissy Squat', 'legs', 'bodyweight', false, 332,
   array['Lean back as knees go forward', 'Hold support', 'Go only as deep as comfortable']::text[],
   array['Hold a support with one hand.', 'Rise on your toes and lean back as your knees move forward.', 'Lower as far as is comfortable.', 'Return to standing.']::text[]),
  ('Pistol Squat', 'legs', 'bodyweight', false, 333,
   array['One leg straight out front', 'Arms forward for balance', 'Control the bottom']::text[],
   array['Stand on one leg with the other held out in front.', 'Squat down on the standing leg.', 'Go as low as you can control.', 'Stand back up. Switch legs.']::text[]),
  ('Belt Squat', 'legs', 'machine', false, 334,
   array['Belt at the hips', 'Stay upright', 'Push through the floor']::text[],
   array['Attach the belt around your hips and stand on the platform.', 'Release the stops.', 'Squat down with your torso upright.', 'Stand up.']::text[]),
  ('Frog Pump', 'legs', 'bodyweight', false, 335,
   array['Soles of the feet together', 'Knees out', 'Squeeze at the top']::text[],
   array['Lie on your back with soles together and knees out.', 'Push your hips up.', 'Squeeze your glutes, then lower.']::text[]),
  ('Donkey Kick', 'legs', 'bodyweight', false, 336,
   array['On hands and knees', 'Knee stays bent', 'Push the heel to the ceiling']::text[],
   array['Start on your hands and knees.', 'Keep the knee bent and lift one leg, heel toward the ceiling.', 'Lower it back. Switch legs.']::text[]),
  ('Fire Hydrant', 'legs', 'bodyweight', false, 337,
   array['Hips stay level', 'Lift the knee out to the side', 'Slow']::text[],
   array['Start on your hands and knees.', 'Lift one bent knee out to the side.', 'Lower it back. Switch sides.']::text[]),
  ('Seated Barbell Press', 'shoulders', 'barbell', false, 403,
   array['Sit tall', 'Bar in a straight line', 'Stop short of locking out']::text[],
   array['Sit on an upright bench with the bar at your collarbones.', 'Press it straight overhead.', 'Lower it back to your collarbones.']::text[]),
  ('Push Press', 'shoulders', 'barbell', false, 404,
   array['Short dip with the legs', 'Drive the bar up', 'Lock out overhead']::text[],
   array['Hold the bar at your collarbones.', 'Dip slightly at the knees.', 'Drive up with your legs and press the bar overhead.', 'Lower it back to your shoulders.']::text[]),
  ('Arnold Press', 'shoulders', 'dumbbell', false, 405,
   array['Start palms facing you', 'Rotate as you press', 'Control the way down']::text[],
   array['Sit with dumbbells at shoulder height, palms toward you.', 'Press up while turning your palms forward.', 'Reverse the turn as you lower.']::text[]),
  ('Machine Shoulder Press', 'shoulders', 'machine', false, 406,
   array['Handles at shoulder height', 'Back on the pad', 'Smooth press']::text[],
   array['Set the seat so the handles are at shoulder height.', 'Press them overhead.', 'Lower slowly.']::text[]),
  ('Cable Lateral Raise', 'shoulders', 'cable', false, 407,
   array['Cable behind or in front of you', 'Lead with the elbow', 'Stop at shoulder height']::text[],
   array['Stand beside a low cable holding the handle in the far hand.', 'Raise your arm out to the side.', 'Stop at shoulder height and lower slowly.', 'Switch sides.']::text[]),
  ('Machine Lateral Raise', 'shoulders', 'machine', false, 408,
   array['Pads on the outside of the arms', 'Lift to shoulder height', 'Slow down']::text[],
   array['Sit with the pads against your upper arms.', 'Raise your arms out to the sides.', 'Lower slowly.']::text[]),
  ('Front Raise', 'shoulders', 'dumbbell', false, 409,
   array['Arms nearly straight', 'Raise to eye level', 'No swinging']::text[],
   array['Hold dumbbells in front of your thighs.', 'Raise one or both to eye level.', 'Lower slowly.']::text[]),
  ('Plate Front Raise', 'shoulders', 'other', false, 410,
   array['Hold the plate at the sides', 'Arms nearly straight', 'Lift to eye level']::text[],
   array['Hold a plate at your thighs with both hands.', 'Raise it to eye level.', 'Lower slowly.']::text[]),
  ('Upright Row', 'shoulders', 'barbell', false, 411,
   array['Hands about shoulder-width', 'Elbows lead', 'Stop at mid-chest']::text[],
   array['Hold the bar at your thighs with hands shoulder-width.', 'Pull it up along your body, elbows leading.', 'Stop at mid-chest.', 'Lower slowly.']::text[]),
  ('Rear Delt Cable Fly', 'shoulders', 'cable', false, 412,
   array['Cables crossed', 'Arms out wide', 'Squeeze the back of the shoulders']::text[],
   array['Set both pulleys at shoulder height and cross the cables.', 'Hold each handle with the opposite hand.', 'Pull your arms out and back.', 'Return slowly.']::text[]),
  ('Pike Push-up', 'shoulders', 'bodyweight', false, 413,
   array['Hips high', 'Head toward the floor between the hands', 'Press back up']::text[],
   array['Start in a push-up position and walk your feet in so your hips rise.', 'Bend your elbows to lower your head toward the floor.', 'Press back up.']::text[]),
  ('Handstand Push-up', 'shoulders', 'bodyweight', false, 414,
   array['Against a wall', 'Hands just wider than shoulders', 'Lower with control']::text[],
   array['Kick up into a handstand against a wall.', 'Lower your head toward the floor.', 'Press back up to straight arms.']::text[]),
  ('Band Pull-Apart', 'shoulders', 'other', false, 415,
   array['Arms straight', 'Pull the band to the chest', 'Squeeze the shoulder blades']::text[],
   array['Hold a band in front of you at shoulder height.', 'Pull it apart until it touches your chest.', 'Return slowly.']::text[]),
  ('External Rotation', 'shoulders', 'cable', false, 416,
   array['Elbow at your side', 'Rotate the forearm out', 'Light weight']::text[],
   array['Stand beside a cable at elbow height, elbow tucked at your side.', 'Rotate your forearm away from your body.', 'Return slowly. Switch sides.']::text[]),
  ('Y-Raise', 'shoulders', 'dumbbell', false, 417,
   array['Lie face down on an incline', 'Arms in a Y shape', 'Thumbs up']::text[],
   array['Lie face down on an incline bench with light dumbbells.', 'Raise your arms up and out in a Y shape.', 'Lower slowly.']::text[]),
  ('Landmine Lateral Raise', 'shoulders', 'barbell', false, 418,
   array['Bar end in one hand', 'Arc out to the side', 'Control']::text[],
   array['Stand beside a landmine and hold the bar end across your body.', 'Raise it out to the side to shoulder height.', 'Lower slowly. Switch sides.']::text[]),
  ('EZ-Bar Curl', 'arms', 'barbell', false, 502,
   array['Grip on the angled part', 'Elbows still', 'Full range']::text[],
   array['Hold an EZ bar with an underhand grip.', 'Curl it up keeping your elbows still.', 'Lower slowly.']::text[]),
  ('Hammer Curl', 'arms', 'dumbbell', false, 503,
   array['Palms face each other', 'Elbows pinned', 'No swinging']::text[],
   array['Hold dumbbells at your sides, palms facing in.', 'Curl them up.', 'Lower slowly.']::text[]),
  ('Incline Dumbbell Curl', 'arms', 'dumbbell', false, 504,
   array['Arms hang behind the body', 'Elbows still', 'Slow lower']::text[],
   array['Sit back on an incline bench with arms hanging.', 'Curl the dumbbells up.', 'Lower all the way down.']::text[]),
  ('Preacher Curl', 'arms', 'barbell', false, 505,
   array['Upper arms flat on the pad', 'Do not lift the elbows', 'Controlled stretch']::text[],
   array['Sit at the preacher bench with arms on the pad.', 'Curl the bar up.', 'Lower slowly until your arms are nearly straight.']::text[]),
  ('Concentration Curl', 'arms', 'dumbbell', false, 506,
   array['Elbow against the inner thigh', 'Curl to the shoulder', 'Squeeze']::text[],
   array['Sit and rest your elbow against your inner thigh.', 'Curl the dumbbell up.', 'Lower slowly. Switch arms.']::text[]),
  ('Cable Curl', 'arms', 'cable', false, 507,
   array['Elbows at your sides', 'Constant tension', 'Squeeze at the top']::text[],
   array['Stand facing a low cable holding a bar.', 'Curl it up keeping your elbows still.', 'Lower slowly.']::text[]),
  ('Spider Curl', 'arms', 'dumbbell', false, 508,
   array['Chest on an incline bench', 'Arms hang straight down', 'Curl and squeeze']::text[],
   array['Lie face down on an incline bench with dumbbells.', 'Let your arms hang.', 'Curl the dumbbells up.', 'Lower slowly.']::text[]),
  ('Reverse Curl', 'arms', 'barbell', false, 509,
   array['Overhand grip', 'Elbows still', 'Slow lower']::text[],
   array['Hold the bar with palms facing down.', 'Curl it up.', 'Lower slowly.']::text[]),
  ('Machine Bicep Curl', 'arms', 'machine', false, 510,
   array['Arms on the pad', 'Full range', 'Slow return']::text[],
   array['Sit with your upper arms on the pad.', 'Curl the handles up.', 'Lower slowly.']::text[]),
  ('Overhead Triceps Extension', 'arms', 'dumbbell', false, 511,
   array['Elbows point up', 'Lower behind the head', 'Straighten fully']::text[],
   array['Hold one dumbbell overhead with both hands.', 'Bend your elbows to lower it behind your head.', 'Straighten your arms to lift it.']::text[]),
  ('Overhead Cable Triceps Extension', 'arms', 'cable', false, 512,
   array['Face away from the cable', 'Elbows near the head', 'Straighten fully']::text[],
   array['Hold a rope from a high or low cable and face away.', 'Start with elbows bent behind your head.', 'Straighten your arms forward and up.', 'Return slowly.']::text[]),
  ('Rope Pushdown', 'arms', 'cable', false, 513,
   array['Elbows at your sides', 'Spread the rope at the bottom', 'Slow up']::text[],
   array['Hold a rope on a high cable.', 'Push it down, spreading the ends at the bottom.', 'Let it rise to about 90 degrees at the elbow.']::text[]),
  ('Single-Arm Pushdown', 'arms', 'cable', false, 514,
   array['Elbow pinned', 'Straighten fully', 'Control']::text[],
   array['Hold a single handle on a high cable.', 'Push down until your arm is straight.', 'Return slowly. Switch arms.']::text[]),
  ('Dumbbell Kickback', 'arms', 'dumbbell', false, 515,
   array['Upper arm parallel to the floor', 'Straighten fully', 'Only the forearm moves']::text[],
   array['Hinge forward with one hand on a bench.', 'Hold your upper arm against your side.', 'Straighten your arm back.', 'Return slowly. Switch arms.']::text[]),
  ('Bench Dip', 'arms', 'bodyweight', false, 516,
   array['Hands on the bench edge', 'Hips close to the bench', 'Lower to 90 degrees']::text[],
   array['Sit on a bench edge with hands beside your hips.', 'Slide your hips off the bench.', 'Bend your elbows to lower.', 'Push back up.']::text[]),
  ('Machine Triceps Dip', 'arms', 'machine', false, 517,
   array['Sit tall', 'Push down', 'Control']::text[],
   array['Sit in the machine holding the handles.', 'Push down until your arms are straight.', 'Return slowly.']::text[]),
  ('Wrist Curl', 'arms', 'dumbbell', false, 518,
   array['Forearms on the thighs', 'Only the wrists move', 'Full range']::text[],
   array['Sit with forearms on your thighs, palms up, holding dumbbells.', 'Curl your wrists up.', 'Lower slowly.']::text[]),
  ('Reverse Wrist Curl', 'arms', 'dumbbell', false, 519,
   array['Palms down', 'Forearms on the thighs', 'Small, slow reps']::text[],
   array['Sit with forearms on your thighs, palms down.', 'Lift the backs of your hands.', 'Lower slowly.']::text[]),
  ('Farmer''s Walk', 'full_body', 'dumbbell', true, 701,
   array['Stand tall', 'Grip hard', 'Short, quick steps']::text[],
   array['Pick up heavy dumbbells or kettlebells.', 'Stand tall with shoulders back.', 'Walk for the distance or time set.', 'Set them down carefully.']::text[]),
  ('Dead Hang', 'arms', 'bodyweight', true, 520,
   array['Full grip on the bar', 'Relax the shoulders', 'Breathe']::text[],
   array['Grip the pull-up bar with both hands.', 'Hang with straight arms.', 'Hold for the time set.']::text[]),
  ('Side Plank', 'core', 'bodyweight', true, 601,
   array['Elbow under the shoulder', 'Hips high', 'Straight line']::text[],
   array['Lie on your side and prop up on your elbow.', 'Lift your hips so your body is straight.', 'Hold, then switch sides.']::text[]),
  ('Crunch', 'core', 'bodyweight', false, 602,
   array['Lower back on the floor', 'Lift the shoulders', 'Do not pull the neck']::text[],
   array['Lie on your back with knees bent.', 'Put your hands lightly by your head.', 'Curl your shoulders off the floor.', 'Lower slowly.']::text[]),
  ('Sit-up', 'core', 'bodyweight', false, 603,
   array['Feet anchored or flat', 'Roll up smoothly', 'Lower with control']::text[],
   array['Lie on your back with knees bent.', 'Sit all the way up.', 'Lower back down slowly.']::text[]),
  ('Bicycle Crunch', 'core', 'bodyweight', false, 604,
   array['Elbow toward the opposite knee', 'Other leg straight', 'Slow and controlled']::text[],
   array['Lie on your back with hands by your head.', 'Bring one knee in as you twist the opposite elbow toward it.', 'Switch sides in a pedalling motion.']::text[]),
  ('Reverse Crunch', 'core', 'bodyweight', false, 605,
   array['Curl the hips off the floor', 'Knees toward the chest', 'Slow down']::text[],
   array['Lie on your back with knees bent and feet up.', 'Curl your hips off the floor toward your chest.', 'Lower slowly.']::text[]),
  ('Lying Leg Raise', 'core', 'bodyweight', false, 606,
   array['Lower back pressed down', 'Legs straight', 'Lower slowly']::text[],
   array['Lie on your back with legs straight.', 'Raise your legs to vertical.', 'Lower them slowly without arching.']::text[]),
  ('Hanging Knee Raise', 'core', 'bodyweight', false, 607,
   array['No swinging', 'Knees to the chest', 'Slow lower']::text[],
   array['Hang from a bar.', 'Raise your knees toward your chest.', 'Lower slowly.']::text[]),
  ('Captain''s Chair Leg Raise', 'core', 'machine', false, 608,
   array['Back against the pad', 'Knees up', 'No swinging']::text[],
   array['Support yourself on the forearm pads with your back on the pad.', 'Raise your knees toward your chest.', 'Lower slowly.']::text[]),
  ('Ab Wheel Rollout', 'core', 'other', false, 609,
   array['Hips and chest move together', 'Keep the back flat', 'Roll only as far as you control']::text[],
   array['Kneel holding the ab wheel under your shoulders.', 'Roll it forward, keeping your back flat.', 'Pull it back to the start.']::text[]),
  ('Mountain Climber', 'core', 'bodyweight', false, 610,
   array['Hips level', 'Knees drive to the chest', 'Quick feet']::text[],
   array['Start in a high plank.', 'Drive one knee toward your chest.', 'Switch legs quickly, like running.']::text[]),
  ('Dead Bug', 'core', 'bodyweight', false, 611,
   array['Lower back pressed down', 'Opposite arm and leg', 'Slow and controlled']::text[],
   array['Lie on your back with arms up and knees bent above your hips.', 'Lower one arm and the opposite leg toward the floor.', 'Return and switch sides.']::text[]),
  ('Bird Dog', 'core', 'bodyweight', false, 612,
   array['Back flat like a table', 'Reach long', 'Pause']::text[],
   array['Start on your hands and knees.', 'Reach one arm forward and the opposite leg back.', 'Pause, then return. Switch sides.']::text[]),
  ('Hollow Body Hold', 'core', 'bodyweight', true, 613,
   array['Lower back pressed down', 'Arms and legs long', 'Breathe']::text[],
   array['Lie on your back and press your lower back down.', 'Lift your shoulders and legs off the floor.', 'Hold for the time set.']::text[]),
  ('V-Up', 'core', 'bodyweight', false, 614,
   array['Legs and arms meet', 'Balance on the hips', 'Lower with control']::text[],
   array['Lie flat with arms overhead.', 'Lift your legs and upper body to meet in the middle.', 'Lower back down slowly.']::text[]),
  ('Flutter Kick', 'core', 'bodyweight', true, 615,
   array['Lower back down', 'Legs straight', 'Small, quick kicks']::text[],
   array['Lie on your back with legs straight and slightly raised.', 'Kick your legs up and down in small movements.', 'Keep going for the time set.']::text[]),
  ('Pallof Press', 'core', 'cable', false, 616,
   array['Stand side-on to the cable', 'Do not let it twist you', 'Press straight out']::text[],
   array['Stand side-on to a cable at chest height, holding the handle at your chest.', 'Press it straight out in front of you.', 'Hold, then bring it back. Switch sides.']::text[]),
  ('Cable Woodchop', 'core', 'cable', false, 617,
   array['Rotate from the torso', 'Arms fairly straight', 'Pivot the back foot']::text[],
   array['Set a cable high and hold the handle with both hands.', 'Pull it down and across your body.', 'Return slowly. Switch sides.']::text[]),
  ('Toe Touch Crunch', 'core', 'bodyweight', false, 618,
   array['Legs straight up', 'Reach for the toes', 'Lower slowly']::text[],
   array['Lie on your back with legs pointing up.', 'Reach up toward your toes.', 'Lower your shoulders back down.']::text[]),
  ('Heel Tap', 'core', 'bodyweight', false, 619,
   array['Shoulders slightly lifted', 'Reach side to side', 'Keep it controlled']::text[],
   array['Lie on your back with knees bent.', 'Lift your shoulders slightly.', 'Reach to touch one heel, then the other.']::text[]),
  ('Plank Shoulder Tap', 'core', 'bodyweight', false, 620,
   array['Feet wide for balance', 'Hips still', 'Tap the opposite shoulder']::text[],
   array['Start in a high plank.', 'Lift one hand and tap the opposite shoulder.', 'Switch hands, keeping your hips still.']::text[]),
  ('Weighted Decline Sit-up', 'core', 'other', false, 621,
   array['Hold a plate at the chest', 'Roll up smoothly', 'Lower slowly']::text[],
   array['Hook your feet on a decline bench.', 'Hold a plate at your chest.', 'Sit up.', 'Lower slowly.']::text[]),
  ('Ab Crunch Machine', 'core', 'machine', false, 622,
   array['Curl the spine', 'Do not pull with the arms', 'Slow return']::text[],
   array['Sit in the machine holding the handles.', 'Curl your torso forward.', 'Return slowly.']::text[]),
  ('Windshield Wiper', 'core', 'bodyweight', false, 623,
   array['Shoulders flat', 'Legs together', 'Slow side to side']::text[],
   array['Lie on your back with arms out and legs up.', 'Lower your legs to one side.', 'Bring them back up and lower to the other side.']::text[]),
  ('Bear Crawl', 'full_body', 'bodyweight', true, 702,
   array['Knees just off the floor', 'Back flat', 'Opposite hand and foot']::text[],
   array['Start on hands and feet with knees just off the floor.', 'Move forward with opposite hand and foot together.', 'Keep going for the distance or time set.']::text[]),
  ('Thruster', 'full_body', 'barbell', false, 703,
   array['Front squat into a press', 'Use the legs to drive', 'One smooth motion']::text[],
   array['Hold the bar at your shoulders.', 'Squat down.', 'Drive up and press the bar overhead in one motion.', 'Lower it to your shoulders.']::text[]),
  ('Dumbbell Thruster', 'full_body', 'dumbbell', false, 704,
   array['Dumbbells at the shoulders', 'Squat then press', 'Stay smooth']::text[],
   array['Hold dumbbells at your shoulders.', 'Squat down.', 'Stand and press them overhead.', 'Lower them to your shoulders.']::text[]),
  ('Power Clean', 'full_body', 'barbell', false, 705,
   array['Bar close to the body', 'Explode with the hips', 'Catch on the shoulders']::text[],
   array['Start as for a deadlift.', 'Pull the bar off the floor and extend your hips hard.', 'Pull yourself under and catch it on your shoulders.', 'Stand up, then lower it.']::text[]),
  ('Hang Clean', 'full_body', 'barbell', false, 706,
   array['Start at the thighs', 'Hips drive', 'Fast elbows']::text[],
   array['Hold the bar at your thighs.', 'Dip, then drive your hips forward.', 'Catch the bar on your shoulders.', 'Stand tall, then lower it.']::text[]),
  ('Clean and Press', 'full_body', 'barbell', false, 707,
   array['Clean first, then press', 'Brace before the press', 'Control the lowering']::text[],
   array['Clean the bar to your shoulders.', 'Press it overhead.', 'Lower it to your shoulders, then to the floor.']::text[]),
  ('Snatch', 'full_body', 'barbell', false, 708,
   array['Wide grip', 'Bar close to the body', 'Catch overhead']::text[],
   array['Grip the bar wide and start as for a deadlift.', 'Pull and extend your hips hard.', 'Pull yourself under and catch the bar overhead.', 'Stand up with it overhead.']::text[]),
  ('Kettlebell Goblet Squat', 'legs', 'other', false, 338,
   array['Kettlebell by the horns', 'Elbows inside the knees', 'Sit tall']::text[],
   array['Hold a kettlebell at your chest.', 'Squat down with your chest up.', 'Stand back up.']::text[]),
  ('Kettlebell Clean', 'full_body', 'other', false, 709,
   array['Hinge, do not squat', 'Keep it close', 'Soft catch']::text[],
   array['Hinge and grip the kettlebell.', 'Drive your hips to pull it up close to your body.', 'Catch it at your shoulder.', 'Lower and repeat.']::text[]),
  ('Kettlebell Snatch', 'full_body', 'other', false, 710,
   array['Hinge and drive', 'Punch through at the top', 'Keep it close']::text[],
   array['Swing the kettlebell back between your legs.', 'Drive your hips to swing it up.', 'Punch your hand up to finish overhead.', 'Bring it back down and repeat.']::text[]),
  ('Turkish Get-up', 'full_body', 'other', false, 711,
   array['Eyes on the weight', 'Arm straight the whole time', 'Move slowly']::text[],
   array['Lie holding a kettlebell straight up in one hand.', 'Roll to your elbow, then your hand.', 'Bridge up, sweep your leg under, and stand.', 'Reverse the steps to lie down.']::text[]),
  ('Kettlebell Deadlift', 'legs', 'other', false, 339,
   array['Kettlebell between the feet', 'Flat back', 'Stand tall']::text[],
   array['Stand over the kettlebell.', 'Hinge and grip the handle.', 'Stand up by driving your hips forward.', 'Lower it back.']::text[]),
  ('Man Maker', 'full_body', 'dumbbell', false, 712,
   array['Push-up, rows, then thruster', 'Keep the core tight', 'Steady pace']::text[],
   array['Start in a plank on two dumbbells.', 'Do a push-up, then row each dumbbell.', 'Jump your feet in and clean the dumbbells.', 'Squat and press them overhead.']::text[]),
  ('Wall Ball', 'full_body', 'other', false, 713,
   array['Squat deep', 'Throw from the legs', 'Catch and go']::text[],
   array['Hold a medicine ball at your chest facing a wall.', 'Squat down.', 'Stand and throw the ball to the target.', 'Catch it and go into the next squat.']::text[]),
  ('Medicine Ball Slam', 'full_body', 'other', false, 714,
   array['Reach overhead', 'Slam hard', 'Squat to pick it up']::text[],
   array['Hold a medicine ball overhead.', 'Slam it down in front of you.', 'Squat to pick it up and repeat.']::text[]),
  ('Sled Push', 'full_body', 'other', true, 715,
   array['Arms extended or bent', 'Low body angle', 'Drive with the legs']::text[],
   array['Hold the sled handles with a forward lean.', 'Drive with your legs to push it.', 'Keep going for the distance or time set.']::text[]),
  ('Sled Pull', 'full_body', 'other', true, 716,
   array['Lean back', 'Hand over hand, or walk backward', 'Steady']::text[],
   array['Hold the rope or handles attached to the sled.', 'Pull it toward you or walk backward.', 'Keep going for the distance or time set.']::text[]),
  ('Battle Ropes', 'full_body', 'other', true, 717,
   array['Athletic stance', 'Waves from the shoulders', 'Keep the rhythm']::text[],
   array['Hold one rope end in each hand.', 'Stand with knees soft.', 'Make waves by moving your arms fast.', 'Keep going for the time set.']::text[]),
  ('Tire Flip', 'full_body', 'other', false, 718,
   array['Chest against the tire', 'Drive with the legs', 'Push it over']::text[],
   array['Squat and grip under the tire.', 'Drive up with your legs and hips.', 'Push the tire over.']::text[]),
  ('Bear Complex', 'full_body', 'barbell', false, 719,
   array['Clean, front squat, press, back squat, press', 'Light weight', 'Steady breathing']::text[],
   array['Clean the bar to your shoulders and front squat.', 'Press it overhead and lower it behind your neck.', 'Back squat and press it overhead.', 'Lower it to the front and repeat.']::text[]),
  ('Squat Thrust', 'full_body', 'bodyweight', false, 720,
   array['Hands down, feet back', 'Feet in, stand', 'Steady pace']::text[],
   array['Squat and put your hands on the floor.', 'Jump your feet back to a plank.', 'Jump them back in and stand up.']::text[]),
  ('Inchworm', 'full_body', 'bodyweight', false, 721,
   array['Legs as straight as you can', 'Walk the hands out', 'Walk them back']::text[],
   array['Stand and fold forward, hands to the floor.', 'Walk your hands out to a plank.', 'Walk them back and stand up.']::text[]),
  ('Devil Press', 'full_body', 'dumbbell', false, 722,
   array['Burpee on the dumbbells', 'Swing them overhead', 'Smooth hinge']::text[],
   array['Do a burpee with your hands on two dumbbells.', 'Jump your feet in.', 'Swing both dumbbells between your legs and up overhead in one move.', 'Lower them and repeat.']::text[]),
  ('Renegade Row', 'full_body', 'dumbbell', false, 723,
   array['Feet wide', 'Hips still', 'Row one side at a time']::text[],
   array['Start in a plank on two dumbbells.', 'Row one dumbbell to your hip.', 'Put it down and row the other.']::text[]),
  ('Outdoor Run', 'cardio', 'other', true, 801,
   array['Relaxed shoulders', 'Short, quick steps', 'Breathe steadily']::text[],
   array['Warm up with a few minutes of walking.', 'Run at the pace set.', 'Cool down with a walk.']::text[]),
  ('Treadmill Walk', 'cardio', 'machine', true, 802,
   array['Stand tall', 'Do not hold the rails', 'Natural stride']::text[],
   array['Start the belt slowly.', 'Walk at the speed and incline set.', 'Slow down gradually to finish.']::text[]),
  ('Incline Treadmill Walk', 'cardio', 'machine', true, 803,
   array['Stand tall', 'Hands off the rails', 'Steady pace']::text[],
   array['Set the incline.', 'Walk at a steady pace.', 'Lower the incline to cool down.']::text[]),
  ('Elliptical', 'cardio', 'machine', true, 804,
   array['Stand tall', 'Push and pull the handles', 'Steady rhythm']::text[],
   array['Step on and hold the handles.', 'Start moving at an easy pace.', 'Keep the resistance and time set.']::text[]),
  ('Stair Climber', 'cardio', 'machine', true, 805,
   array['Upright posture', 'Light hands on the rails', 'Whole foot on the step']::text[],
   array['Step on and hold the rails lightly.', 'Start at an easy speed.', 'Climb for the time set.']::text[]),
  ('Air Bike', 'cardio', 'machine', true, 806,
   array['Push and pull the arms', 'Drive with the legs', 'Pace yourself']::text[],
   array['Sit and set the seat height.', 'Pedal while pushing and pulling the handles.', 'Keep going for the time or distance set.']::text[]),
  ('Spin Bike', 'cardio', 'machine', true, 807,
   array['Seat at hip height', 'Light grip', 'Smooth pedalling']::text[],
   array['Set the seat and handlebars.', 'Pedal at the resistance and cadence set.', 'Ease off to cool down.']::text[]),
  ('SkiErg', 'cardio', 'machine', true, 808,
   array['Hinge and pull down', 'Arms and hips together', 'Steady rhythm']::text[],
   array['Stand facing the machine holding both handles overhead.', 'Pull down while hinging at the hips.', 'Return to tall and repeat.']::text[]),
  ('Jumping Jacks', 'cardio', 'bodyweight', true, 809,
   array['Light on the feet', 'Arms fully overhead', 'Steady rhythm']::text[],
   array['Stand with feet together and arms at your sides.', 'Jump your feet out as your arms go overhead.', 'Jump back to the start and repeat.']::text[]),
  ('High Knees', 'cardio', 'bodyweight', true, 810,
   array['Knees to hip height', 'Pump the arms', 'Stay on the balls of the feet']::text[],
   array['Run in place.', 'Drive each knee up to hip height.', 'Keep going for the time set.']::text[]),
  ('Butt Kicks', 'cardio', 'bodyweight', true, 811,
   array['Heels to the glutes', 'Quick feet', 'Tall posture']::text[],
   array['Run in place.', 'Kick each heel up toward your glutes.', 'Keep going for the time set.']::text[]),
  ('Skater Jumps', 'cardio', 'bodyweight', true, 812,
   array['Land softly on one leg', 'Swing the arms', 'Side to side']::text[],
   array['Jump sideways onto one leg.', 'Land softly and bring the other leg behind.', 'Jump back to the other side.']::text[]),
  ('Shadow Boxing', 'cardio', 'bodyweight', true, 813,
   array['Hands up', 'Light on your feet', 'Punch and move']::text[],
   array['Stand in a boxing stance with hands up.', 'Throw punches and move your feet.', 'Keep going for the time set.']::text[]),
  ('Swimming', 'cardio', 'other', true, 814,
   array['Long strokes', 'Steady breathing', 'Relaxed kick']::text[],
   array['Warm up with easy lengths.', 'Swim at the pace and distance set.', 'Cool down with easy lengths.']::text[]),
  ('Sprint Intervals', 'cardio', 'other', true, 815,
   array['Warm up first', 'All-out on the sprint', 'Recover fully']::text[],
   array['Warm up for several minutes.', 'Sprint hard for the time set.', 'Walk or jog to recover.', 'Repeat for the rounds set.']::text[]),
  ('Brisk Walk', 'cardio', 'other', true, 816,
   array['Swing the arms', 'Quick steps', 'Tall posture']::text[],
   array['Walk at a pace that raises your breathing.', 'Keep going for the time set.']::text[]),
  ('Hiking', 'cardio', 'other', true, 817,
   array['Steady pace on hills', 'Short steps uphill', 'Stay hydrated']::text[],
   array['Start on easy ground.', 'Keep a pace you can hold.', 'Rest when you need to.']::text[]),
  ('Cycling', 'cardio', 'other', true, 818,
   array['Relaxed upper body', 'Smooth pedalling', 'Wear a helmet']::text[],
   array['Set your seat at hip height.', 'Ride at the pace and distance set.', 'Ease off to cool down.']::text[]),
  ('Double-Unders', 'cardio', 'other', false, 819,
   array['Jump a little higher', 'Fast wrists', 'Stay relaxed']::text[],
   array['Jump rope as normal.', 'Jump a little higher and spin the rope twice under your feet.', 'Keep a steady rhythm.']::text[]),
  ('Star Jump', 'cardio', 'bodyweight', false, 820,
   array['Explode up', 'Arms and legs wide', 'Land softly']::text[],
   array['Squat slightly.', 'Jump up, spreading your arms and legs wide.', 'Land softly with feet together.']::text[]),
  ('Tuck Jump', 'cardio', 'bodyweight', false, 821,
   array['Knees to the chest', 'Land softly', 'Reset each rep']::text[],
   array['Stand with feet hip-width.', 'Jump and pull your knees to your chest.', 'Land softly and repeat.']::text[]),
  ('Stair Running', 'cardio', 'other', true, 822,
   array['Whole foot on each step', 'Pump the arms', 'Walk down carefully']::text[],
   array['Run up the stairs.', 'Walk down to recover.', 'Repeat for the time or rounds set.']::text[]),
  ('Foam Rolling', 'full_body', 'other', true, 724,
   array['Slow rolls', 'Pause on tight spots', 'Breathe']::text[],
   array['Place the roller under the muscle.', 'Roll slowly back and forth.', 'Pause on tight spots for a few breaths.']::text[]),
  ('World''s Greatest Stretch', 'full_body', 'bodyweight', false, 725,
   array['Long lunge', 'Elbow to the instep', 'Rotate and reach up']::text[],
   array['Step into a long lunge.', 'Put the same-side elbow toward your front foot.', 'Rotate and reach that arm to the ceiling.', 'Switch sides.']::text[]),
  ('Cat-Cow', 'core', 'bodyweight', false, 624,
   array['Move with your breath', 'Round, then arch', 'Slow']::text[],
   array['Start on your hands and knees.', 'Round your back as you breathe out.', 'Arch it as you breathe in.']::text[]),
  ('Child''s Pose', 'full_body', 'bodyweight', true, 726,
   array['Hips to heels', 'Arms long', 'Breathe deeply']::text[],
   array['Kneel and sit your hips toward your heels.', 'Reach your arms forward on the floor.', 'Rest and breathe for the time set.']::text[]),
  ('Hip Flexor Stretch', 'legs', 'bodyweight', true, 340,
   array['Kneeling lunge', 'Squeeze the back glute', 'Tall torso']::text[],
   array['Kneel on one knee with the other foot in front.', 'Squeeze the back glute and shift forward gently.', 'Hold, then switch sides.']::text[]),
  ('Hamstring Stretch', 'legs', 'bodyweight', true, 341,
   array['Straight leg', 'Hinge from the hips', 'Gentle hold']::text[],
   array['Sit or stand with one leg straight.', 'Hinge forward until you feel a stretch.', 'Hold, then switch legs.']::text[]),
  ('Pigeon Stretch', 'legs', 'bodyweight', true, 342,
   array['Front shin across', 'Hips square', 'Relax into it']::text[],
   array['From a plank, bring one knee forward behind your wrist.', 'Stretch the other leg back.', 'Lower your hips and hold. Switch sides.']::text[]),
  ('Thoracic Rotation', 'back', 'bodyweight', false, 220,
   array['On hands and knees', 'Follow the elbow with your eyes', 'Slow']::text[],
   array['Start on your hands and knees with one hand behind your head.', 'Rotate that elbow toward the ceiling.', 'Return and repeat. Switch sides.']::text[]),
  ('Shoulder Dislocate', 'shoulders', 'other', false, 419,
   array['Wide grip on a band or stick', 'Arms straight', 'Slow over and back']::text[],
   array['Hold a band or stick with a wide grip.', 'Raise it over your head and behind you.', 'Bring it back to the front.']::text[])
) as v(name, grp, equip, timed, ord, cues, steps)
where not exists (select 1 from exercises e where e.gym_id is null and lower(e.name) = lower(v.name));

-- A gym's own same-named exercise wins, for that gym. The overlay needs an
-- author; the gym's owner is the honest one (it is their list being tidied).
insert into gym_exercise_media (gym_id, exercise_id, hidden, created_by)
select own.gym_id, lib.id, true,
       (select r.user_id from gym_roles r
         where r.gym_id = own.gym_id and r.role = 'admin' and r.status = 'active'
         order by r.user_id limit 1)
from exercises own
join exercises lib on lib.gym_id is null and lower(lib.name) = lower(own.name)
where own.gym_id is not null
  and lib.created_by is null
  and exists (select 1 from gym_roles r where r.gym_id = own.gym_id and r.role = 'admin' and r.status = 'active')
on conflict (gym_id, exercise_id) do update set hidden = true;

create or replace function migration_0126_applied() returns boolean
language sql immutable as $marker$ select true $marker$;
revoke all on function migration_0126_applied() from public, anon;
grant execute on function migration_0126_applied() to authenticated;
comment on function migration_0126_applied() is
  'Marker for scripts/probe-migrations.py. Delete only alongside the probe entry.';

-- VERIFICATION: scripts/sql/verify/verify0126.sql
