import { motion, AnimatePresence } from 'framer-motion';
import { useState, useEffect, useCallback } from 'react';
import { createPortal } from 'react-dom';
import { Link } from 'react-router-dom';
import Button from '../components/ui/Button';
import Input from '../components/ui/Input';
import ConfirmDialog from '../components/ui/ConfirmDialog';
import ImageField from '../components/ui/ImageField';
import Pagination from '../components/ui/Pagination';
import {
  PageHeader, StatTiles, Section, EmptyState, CardGrid, TileCard, PageSummary,
  SectionTabs,
} from '../components/ui/kit';
import { usePaged } from '../hooks/usePaged';
import FormField, { SectionLabel, FieldDivider } from '../components/ui/FormField';
import DatePicker from '../components/ui/DatePicker';
import TimePicker from '../components/ui/TimePicker';
import {
  Plus, Edit2, Trash2, X, Calendar, MapPin, Users, Clock, Bell, ChevronRight, Ban,
} from 'lucide-react';
import { showToast } from '../utils/toast';
import {
  listEvents, listRegistrations, listEventRegistrations, createEvent, updateEvent,
  deleteEvent, eventStatus, type EventRow, type EventStatus,
} from '../lib/api/events';
import { listMembers } from '../lib/api/members';

/**
 * Gym events — real rows in `events` (migration 0014).
 *
 * Replaces a localStorage page whose headcounts were invented: `registered` was
 * a literal in the fixture, and the attendee list was generated by slicing a
 * hardcoded array of twenty names. Both now come from `event_registrations`, so
 * an event with no signups shows zero instead of a plausible number.
 *
 * The old "Announcements" tab was a second broadcast composer sitting alongside
 * the real one at /notifications. Duplicated composers mean staff can't tell
 * which one actually sends, so it's a link now, not a copy.
 *
 * Status is derived from `starts_at`, never stored — see the migration.
 */

/** Inputs sit inset against the raised modal panel, matching Members and Trainers. */
const INSET = { background: 'var(--color-bg)' };

const emptyForm = {
  title: '', description: '', date: '', time: '', location: '', capacity: '30', duration: '60',
  // Added in 0057. A member reading an event listing decides on four things the
  // old form could not express: is this for someone like me, what do I need to
  // bring, does it cost anything, and who do I ask.
  whoIsItFor: '', whatToBring: '', fee: '', contact: '', isFeatured: false, imageUrl: '',
};

const STATUS_STYLE: Record<EventStatus, { bg: string; color: string }> = {
  Upcoming: { bg: 'var(--color-primary-light)', color: 'var(--color-primary)' },
  Ongoing: { bg: 'var(--color-primary-light)', color: 'var(--color-primary)' },
  Completed: { bg: 'rgba(148,163,184,0.15)', color: 'var(--color-text-muted)' },
  Cancelled: { bg: 'rgba(148,163,184,0.15)', color: 'var(--color-text-muted)' },
};

/** Local datetime -> ISO, without toISOString()'s UTC shift on the date part. */
function toTimestamp(date: string, time: string): string {
  const [y, m, d] = date.split('-').map(Number);
  const [hh, mm] = time.split(':').map(Number);
  return new Date(y, m - 1, d, hh || 0, mm || 0).toISOString();
}

function splitTimestamp(iso: string): { date: string; time: string } {
  const d = new Date(iso);
  const pad = (n: number) => String(n).padStart(2, '0');
  return {
    date: `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`,
    time: `${pad(d.getHours())}:${pad(d.getMinutes())}`,
  };
}

/** Today as YYYY-MM-DD, for the date picker's floor. Never toISOString(). */
function todayKey(): string {
  const d = new Date();
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`;
}

/**
 * When the event finishes, from the start time and duration.
 *
 * Duration is entered in minutes, which is the right thing to store and the
 * wrong thing to reason about — "60" tells you nothing about when the room is
 * free again. Null whenever either input is missing, so it never guesses.
 */
function endTimeLabel(time: string, durationMinutes: string): string | null {
  if (!time) return null;
  const [hh, mm] = time.split(':').map(Number);
  const mins = Number(durationMinutes);
  if (!Number.isFinite(hh) || !Number.isFinite(mins) || mins <= 0) return null;
  const d = new Date(2000, 0, 1, hh, mm || 0);
  d.setMinutes(d.getMinutes() + mins);
  return d.toLocaleTimeString('en-PH', { hour: 'numeric', minute: '2-digit' });
}

/** Announcements and Events are one section — see SectionTabs for why the
 *  records stay in separate tables. */
const COMMS_TABS = [
  { label: 'Announcements', to: '/notifications' },
  { label: 'Events', to: '/events' },
];

export default function Events() {
  const [events, setEvents] = useState<EventRow[]>([]);
  const [counts, setCounts] = useState<Record<string, number>>({});
  const [names, setNames] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);

  const [showModal, setShowModal] = useState(false);
  const [editing, setEditing] = useState<EventRow | null>(null);
  const [form, setForm] = useState(emptyForm);

  const [errors, setErrors] = useState<Record<string, string>>({});
  const [toCancel, setToCancel] = useState<EventRow | null>(null);
  const [toDelete, setToDelete] = useState<EventRow | null>(null);

  const [attendeesFor, setAttendeesFor] = useState<EventRow | null>(null);
  const [attendees, setAttendees] = useState<{ id: string; name: string; at: string }[]>([]);

  const endsAt = endTimeLabel(form.time, form.duration);

  const load = useCallback(async () => {
    setLoading(true);
    try {
      const [rows, regs, members] = await Promise.all([
        listEvents(),
        listRegistrations().catch(() => []),
        listMembers().catch(() => []),
      ]);
      setEvents(rows);

      const tally: Record<string, number> = {};
      for (const r of regs) tally[r.event_id] = (tally[r.event_id] ?? 0) + 1;
      setCounts(tally);

      const nameById: Record<string, string> = {};
      for (const m of members) nameById[m.profile.id] = `${m.profile.first_name} ${m.profile.last_name}`;
      setNames(nameById);
    } catch (err) {
      showToast(err instanceof Error ? err.message : 'Failed to load events', 'error');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { load(); }, [load]);

  const openAdd = () => { setEditing(null); setForm(emptyForm); setErrors({}); setShowModal(true); };

  const openEdit = (evt: EventRow) => {
    const { date, time } = splitTimestamp(evt.starts_at);
    setEditing(evt);
    setErrors({});
    setForm({
      title: evt.title,
      description: evt.description ?? '',
      date,
      time,
      location: evt.location ?? '',
      capacity: String(evt.capacity),
      whoIsItFor: evt.who_is_it_for ?? '',
      whatToBring: evt.what_to_bring ?? '',
      // NULL fee means free; 0 means deliberately priced at zero. An empty
      // string round-trips back to NULL, so the distinction survives an edit.
      fee: evt.fee == null ? '' : String(evt.fee),
      contact: evt.contact ?? '',
      isFeatured: evt.is_featured ?? false,
      imageUrl: evt.image_url ?? '',
      duration: String(evt.duration_minutes),
    });
    setShowModal(true);
  };

  const handleSave = async () => {
    // Marked against the field that's missing, not just announced in a toast
    // that vanishes before you've found which box it meant.
    const next: Record<string, string> = {};
    if (!form.title.trim()) next.title = 'Give the event a name.';
    if (!form.date) next.date = 'Pick a date.';
    if (!form.time) next.time = 'Pick a start time.';
    setErrors(next);
    if (Object.keys(next).length > 0) {
      return showToast('Title, date and time are required', 'error');
    }

    setSaving(true);
    try {
      const payload = {
        title: form.title.trim(),
        description: form.description.trim() || null,
        starts_at: toTimestamp(form.date, form.time),
        duration_minutes: Number(form.duration) || 60,
        location: form.location.trim() || null,
        capacity: Number(form.capacity) || 30,
        who_is_it_for: form.whoIsItFor.trim() || null,
        what_to_bring: form.whatToBring.trim() || null,
        fee: form.fee.trim() === '' ? null : Number(form.fee),
        contact: form.contact.trim() || null,
        is_featured: form.isFeatured,
        // Empty string means "no picture" and must be stored as NULL — an
        // empty src renders the browser's broken-image glyph on every phone.
        image_url: form.imageUrl.trim() || null,
      };
      if (editing) {
        await updateEvent(editing.id, payload);
        showToast('Event updated', 'success');
      } else {
        await createEvent(payload);
        showToast('Event created', 'success');
      }
      setShowModal(false);
      await load();
    } catch (err) {
      showToast(err instanceof Error ? err.message : 'Failed to save event', 'error');
    } finally {
      setSaving(false);
    }
  };

  // Cancel and delete used `window.confirm` — an OS dialog in the middle of a
  // themed app, with no way to say which button is the destructive one. Every
  // other destructive action in the admin goes through ConfirmDialog.
  const handleCancelEvent = async () => {
    const evt = toCancel;
    if (!evt) return;
    try {
      await updateEvent(evt.id, { cancelled: !evt.cancelled });
      showToast(evt.cancelled ? 'Event reinstated' : 'Event cancelled', 'success');
      setToCancel(null);
      await load();
    } catch (err) {
      showToast(err instanceof Error ? err.message : 'Failed to update event', 'error');
    }
  };

  const handleDelete = async () => {
    const evt = toDelete;
    if (!evt) return;
    try {
      await deleteEvent(evt.id);
      showToast('Event deleted', 'success');
      setToDelete(null);
      await load();
    } catch (err) {
      showToast(err instanceof Error ? err.message : 'Failed to delete event', 'error');
    }
  };

  const openAttendees = async (evt: EventRow) => {
    setAttendeesFor(evt);
    setAttendees([]);
    try {
      const regs = await listEventRegistrations(evt.id);
      setAttendees(regs.map((r) => ({
        id: r.id,
        name: names[r.member_id] ?? 'Member',
        at: new Date(r.registered_at).toLocaleDateString(),
      })));
    } catch (err) {
      showToast(err instanceof Error ? err.message : 'Failed to load attendees', 'error');
    }
  };

  const paged = usePaged(events, 12);

  return (
    <div className="space-y-4">
      <SectionTabs tabs={COMMS_TABS} />
      <PageHeader
        title="Events"
        subtitle="Gym events and member signups"
        actions={
          <>
            <Link to="/notifications"
              className="flex items-center gap-1.5 h-9 px-3 rounded-lg text-[11px] font-semibold"
              style={{ background: 'var(--color-surface-high)', color: 'var(--color-text-secondary)', border: '1px solid var(--color-border)' }}>
              <Bell size={13} /> Announce <ChevronRight size={12} />
            </Link>
            <Button variant="primary" size="sm" onClick={openAdd}>
              <Plus size={15} className="mr-1" /> New event
            </Button>
          </>
        }
      />

      <StatTiles items={[
        { label: 'Events', value: events.length, icon: Calendar },
        { label: 'Upcoming', value: events.filter((e) => eventStatus(e) === 'Upcoming').length, icon: Clock },
        { label: 'Signups', value: Object.values(counts).reduce((s, n) => s + n, 0), icon: Users },
        {
          label: 'Full',
          value: events.filter((e) => (counts[e.id] ?? 0) >= e.capacity).length,
          icon: Users,
          tone: events.some((e) => (counts[e.id] ?? 0) >= e.capacity) ? 'secondary' : 'primary',
        },
      ]} />

      <Section title="All events" icon={Calendar} count={events.length}
        hint="click the headcount to see who signed up">
        {loading ? (
          <p className="text-xs" style={{ color: 'var(--color-text-muted)' }}>Loading events…</p>
        ) : events.length === 0 ? (
          <EmptyState
            icon={Calendar}
            title="No events yet"
            hint="Create one and it appears for every member in the phone app."
            action={<Button variant="primary" size="sm" onClick={openAdd}><Plus size={14} /> New event</Button>}
          />
        ) : (
          <>
            <CardGrid min={300}>
              {paged.visible.map((evt) => {
                const status = eventStatus(evt);
                const style = STATUS_STYLE[status];
                const registered = counts[evt.id] ?? 0;
                const full = registered >= evt.capacity;
                // A capacity bar reads faster than "12/20" alone, and it is the
                // same two numbers — nothing new is being claimed.
                const share = evt.capacity > 0 ? Math.min(100, (registered / evt.capacity) * 100) : 0;
                return (
                  <TileCard key={evt.id} dim={evt.cancelled} accent={full && !evt.cancelled}>
                    {/* Only when the gym chose one — never a stock image. */}
                    {evt.image_url && (
                      <img src={evt.image_url} alt="" loading="lazy"
                        className="w-full rounded-lg object-cover mb-2"
                        style={{ aspectRatio: '16 / 9', background: 'var(--color-bg)' }} />
                    )}
                    <div className="flex items-start justify-between gap-2">
                      <h3 className="text-[13px] font-bold text-white flex-1 leading-snug">{evt.title}</h3>
                      <span className="text-[9px] px-1.5 py-0.5 rounded-full font-semibold flex-shrink-0"
                        style={{ background: style.bg, color: style.color }}>
                        {status}
                      </span>
                    </div>

                    {evt.description && (
                      <p className="text-[10px] mt-1 line-clamp-2" style={{ color: 'var(--color-text-muted)' }}>
                        {evt.description}
                      </p>
                    )}

                    <p className="text-[10px] mt-2 flex items-center gap-2 flex-wrap" style={{ color: 'var(--color-text-muted)' }}>
                      <span className="flex items-center gap-1">
                        <Calendar size={10} />
                        {new Date(evt.starts_at).toLocaleDateString('en-PH', { month: 'short', day: 'numeric' })}
                      </span>
                      <span className="flex items-center gap-1">
                        <Clock size={10} />
                        {new Date(evt.starts_at).toLocaleTimeString([], { hour: 'numeric', minute: '2-digit' })}
                      </span>
                      {evt.location && (
                        <span className="flex items-center gap-1 truncate">
                          <MapPin size={10} /> {evt.location}
                        </span>
                      )}
                    </p>

                    {/* Real headcount from event_registrations */}
                    <button onClick={() => openAttendees(evt)}
                      className="w-full mt-2.5 px-2.5 py-2 rounded-lg text-left"
                      style={{ background: 'var(--color-surface-high)' }}>
                      <span className="flex items-center justify-between">
                        <span className="text-[10px] flex items-center gap-1.5" style={{ color: 'var(--color-text-muted)' }}>
                          <Users size={11} /> Registered
                        </span>
                        <span className="text-[11px] font-bold tabular-nums"
                          style={{ color: full ? 'var(--color-secondary)' : 'var(--color-primary)' }}>
                          {registered}/{evt.capacity}
                        </span>
                      </span>
                      <span className="block mt-1.5 h-1 rounded-full overflow-hidden"
                        style={{ background: 'var(--color-border)' }}>
                        <span className="block h-full rounded-full"
                          style={{ width: `${share}%`, background: full ? 'var(--color-secondary)' : 'var(--color-primary)' }} />
                      </span>
                    </button>

                    <div className="flex gap-1.5 mt-2.5">
                      <Button variant="ghost" size="sm" className="!text-[10px] flex-1" onClick={() => openEdit(evt)}>
                        <Edit2 size={11} className="mr-1" /> Edit
                      </Button>
                      {/* Cancelling keeps the event and every registration;
                          deleting removes both, so they are different buttons. */}
                      <Button variant="ghost" size="sm" className="!text-[10px] flex-1" onClick={() => setToCancel(evt)}>
                        <Ban size={11} className="mr-1" /> {evt.cancelled ? 'Reinstate' : 'Cancel'}
                      </Button>
                      <Button variant="ghost" size="sm" className="!text-[10px]" title="Delete event" onClick={() => setToDelete(evt)}>
                        <Trash2 size={11} style={{ color: 'var(--color-secondary)' }} />
                      </Button>
                    </div>
                  </TileCard>
                );
              })}
            </CardGrid>
            <div className="flex items-center justify-between mt-3">
              <PageSummary page={paged.page} perPage={paged.perPage} total={paged.total} noun="events" />
              <Pagination currentPage={paged.page} totalItems={paged.total}
                itemsPerPage={paged.perPage} onPageChange={paged.setPage} />
            </div>
          </>
        )}
      </Section>

      <ConfirmDialog
        isOpen={!!toCancel}
        onClose={() => setToCancel(null)}
        onConfirm={handleCancelEvent}
        title={toCancel?.cancelled ? 'Reinstate Event' : 'Cancel Event'}
        message={
          toCancel?.cancelled
            ? `Put "${toCancel?.title}" back on? Members will see it as upcoming again.`
            : `Cancel "${toCancel?.title ?? 'this event'}"? It stays visible to members as cancelled, and everyone who signed up keeps their registration record. Nothing is deleted.`
        }
        confirmText={toCancel?.cancelled ? 'Reinstate' : 'Cancel event'}
        cancelText="Never mind"
        type={toCancel?.cancelled ? 'info' : 'warning'}
      />

      <ConfirmDialog
        isOpen={!!toDelete}
        onClose={() => setToDelete(null)}
        onConfirm={handleDelete}
        title="Delete Event"
        message={
          (counts[toDelete?.id ?? ''] ?? 0) > 0
            ? `Delete "${toDelete?.title}"? This also removes ${counts[toDelete!.id]} registration${counts[toDelete!.id] === 1 ? '' : 's'} — the members who signed up lose the record. Cancelling instead keeps it.`
            : `Delete "${toDelete?.title}"? Nobody has signed up, so nothing else is affected.`
        }
        confirmText="Delete"
        type="danger"
      />

      {/* Add / Edit modal */}
      {createPortal(
        <AnimatePresence>
          {showModal && (
            <>
              <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
                onClick={() => setShowModal(false)}
                className="fixed inset-0 bg-black/80 backdrop-blur-sm z-[200]" />
              <div className="fixed inset-0 flex items-center justify-center z-[200] p-4">
                <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.95 }}
                  className="w-full max-w-md rounded-2xl overflow-hidden"
                  style={{ background: 'var(--color-surface-raised)', border: '1px solid var(--color-border)' }}
                  onClick={(e) => e.stopPropagation()}>
                  <div className="p-5 flex items-center justify-between" style={{ borderBottom: '1px solid var(--color-border)' }}>
                    <h2 className="text-base font-bold text-white">{editing ? 'Edit Event' : 'New Event'}</h2>
                    <button onClick={() => setShowModal(false)} className="text-gray-400 hover:text-white">
                      <X size={20} />
                    </button>
                  </div>
                  <div className="p-5 space-y-4 max-h-[65vh] overflow-y-auto scrollbar-thin scrollbar-thumb-dark-border">
                    <SectionLabel>Details</SectionLabel>
                    <FormField label="Event title" required error={errors.title}>
                      <Input style={INSET} type="text" value={form.title} placeholder="e.g. Summer Fitness Challenge"
                        onChange={(e) => setForm({ ...form, title: e.target.value })} />
                    </FormField>
                    <FormField label="Description" hint="Shown to members in the app.">
                      <textarea value={form.description} placeholder="What is it, who is it for?" rows={3}
                        onChange={(e) => setForm({ ...form, description: e.target.value })}
                        className="w-full rounded-xl px-4 py-3 text-white text-sm resize-none"
                        style={{ background: 'var(--color-bg)', border: '1px solid var(--color-border)' }} />
                    </FormField>

                    <FieldDivider />
                    <SectionLabel>Date &amp; Time</SectionLabel>
                    <div className="grid grid-cols-2 gap-3">
                      {/* Our own picker, not <input type="date">. The native one
                          drops a white Chrome-styled calendar over the app and
                          `color-scheme` is the only thing CSS can change about it. */}
                      <FormField label="Date" required error={errors.date}>
                        <DatePicker value={form.date} min={editing ? undefined : todayKey()}
                          onChange={(v) => setForm({ ...form, date: v })} />
                      </FormField>
                      <FormField label="Start time" required error={errors.time}>
                        <TimePicker value={form.time} onChange={(v) => setForm({ ...form, time: v })} />
                      </FormField>
                    </div>
                    <FormField
                      label="Duration (minutes)"
                      hint={endsAt ? `Finishes around ${endsAt}.` : 'How long the event runs.'}
                    >
                      <Input style={INSET} type="number" min="15" step="15" value={form.duration} placeholder="60"
                        onChange={(e) => setForm({ ...form, duration: e.target.value })} />
                    </FormField>

                    <FieldDivider />
                    <SectionLabel>Location &amp; Capacity</SectionLabel>
                    <FormField label="Location" hint="Leave blank if it's at the gym.">
                      <Input style={INSET} type="text" value={form.location} placeholder="e.g. Main floor, Mamburao"
                        onChange={(e) => setForm({ ...form, location: e.target.value })} />
                    </FormField>
                    <FormField label="Capacity (people)" hint="Members can sign up until this is reached.">
                      <Input style={INSET} type="number" min="1" value={form.capacity} placeholder="30"
                        onChange={(e) => setForm({ ...form, capacity: e.target.value })} />
                    </FormField>

                    <FieldDivider />
                    <SectionLabel>Member Information</SectionLabel>

                    <FormField
                      label="Intended Audience"
                      hint="The single most useful line. Saying everyone is welcome and no experience is needed brings people in; leaving it blank quietly keeps beginners away."
                    >
                      <Input style={INSET} type="text" value={form.whoIsItFor}
                        placeholder="e.g. Everyone — half the group will be first-timers"
                        onChange={(e) => setForm({ ...form, whoIsItFor: e.target.value })} />
                    </FormField>

                    <FormField label="Items to Bring" hint="Water, a towel, flat shoes — whatever they will wish they had.">
                      <Input style={INSET} type="text" value={form.whatToBring}
                        placeholder="e.g. Water, a towel, shoes you can move in"
                        onChange={(e) => setForm({ ...form, whatToBring: e.target.value })} />
                    </FormField>

                    <FormField
                      label="Fee"
                      hint={
                        form.fee.trim() === ''
                          ? 'Blank means free, and the app says "Free" rather than "₱0".'
                          : Number(form.fee) === 0
                            ? 'Zero shows as "₱0" — use blank if you mean free.'
                            : 'Members pay at the desk; the app does not take payments.'
                      }
                    >
                      <Input style={INSET} type="number" min="0" step="50" value={form.fee}
                        placeholder="Leave blank if free"
                        onChange={(e) => setForm({ ...form, fee: e.target.value })} />
                    </FormField>

                    <FormField label="Contact Person" hint="Shown to members who have a question before signing up.">
                      <Input style={INSET} type="text" value={form.contact}
                        placeholder="e.g. Ask at the front desk, or message us on Facebook"
                        onChange={(e) => setForm({ ...form, contact: e.target.value })} />
                    </FormField>

                    <ImageField
                      value={form.imageUrl}
                      onChange={(imageUrl) => setForm({ ...form, imageUrl })}
                      kind="events"
                      label="Event picture"
                      hint="A poster or photo, shown with the event in the member app."
                    />

                    <label className="flex items-start gap-2.5 cursor-pointer pt-1">
                      <input type="checkbox" checked={form.isFeatured} className="mt-0.5"
                        onChange={(e) => setForm({ ...form, isFeatured: e.target.checked })} />
                      <span className="text-[11px] leading-relaxed" style={{ color: 'var(--color-text-secondary)' }}>
                        <strong className="text-white">Feature this event.</strong> Pins it to the top of the
                        members' Events screen. Use it sparingly — if everything is featured, nothing is.
                      </span>
                    </label>
                  </div>
                  <div className="p-5 flex gap-3" style={{ borderTop: '1px solid var(--color-border)' }}>
                    <Button variant="ghost" className="flex-1" onClick={() => setShowModal(false)}>Cancel</Button>
                    <Button variant="primary" className="flex-1" onClick={handleSave} disabled={saving}>
                      {saving ? 'Saving…' : editing ? 'Save Changes' : 'Create Event'}
                    </Button>
                  </div>
                </motion.div>
              </div>
            </>
          )}
        </AnimatePresence>,
        document.body
      )}

      {/* Attendees modal */}
      {createPortal(
        <AnimatePresence>
          {attendeesFor && (
            <>
              <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}
                onClick={() => setAttendeesFor(null)}
                className="fixed inset-0 bg-black/80 backdrop-blur-sm z-[200]" />
              <div className="fixed inset-0 flex items-center justify-center z-[200] p-4">
                <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.95 }}
                  className="w-full max-w-sm rounded-2xl overflow-hidden"
                  style={{ background: 'var(--color-surface)', border: '1px solid var(--color-border)' }}
                  onClick={(e) => e.stopPropagation()}>
                  <div className="p-5 flex items-center justify-between" style={{ borderBottom: '1px solid var(--color-border)' }}>
                    <div>
                      <h2 className="text-sm font-bold text-white">{attendeesFor.title}</h2>
                      <p className="text-[10px]" style={{ color: 'var(--color-text-muted)' }}>
                        {attendees.length} registered
                      </p>
                    </div>
                    <button onClick={() => setAttendeesFor(null)} className="text-gray-400 hover:text-white">
                      <X size={20} />
                    </button>
                  </div>
                  <div className="p-4 max-h-[55vh] overflow-y-auto space-y-2">
                    {attendees.length === 0 ? (
                      <p className="text-[11px] text-center py-8" style={{ color: 'var(--color-text-muted)' }}>
                        Nobody has signed up yet.
                      </p>
                    ) : attendees.map((a) => (
                      <div key={a.id} className="flex items-center gap-3 p-2.5 rounded-xl"
                        style={{ background: 'var(--color-bg)', border: '1px solid var(--color-border)' }}>
                        <div className="w-8 h-8 rounded-full flex items-center justify-center text-white text-[10px] font-bold"
                          style={{ background: 'var(--color-primary)' }}>
                          {a.name.split(' ').map(n => n[0]).join('').slice(0, 2).toUpperCase()}
                        </div>
                        <div className="flex-1 min-w-0">
                          <p className="text-[11px] font-semibold text-white truncate">{a.name}</p>
                          <p className="text-[9px]" style={{ color: 'var(--color-text-muted)' }}>Signed up {a.at}</p>
                        </div>
                      </div>
                    ))}
                  </div>
                </motion.div>
              </div>
            </>
          )}
        </AnimatePresence>,
        document.body
      )}
    </div>
  );
}
